### ISSUE TITLE
ButtonGroup Alignment bug

### ISSUE THREAD

**Issue by astanciu** [auth0/cosmos#1001]
This code:
```
        <ButtonGroup align="right">
          <Button icon='pencil' href={`/#/roles/${role.id}`} />
          <Button icon='delete' onClick={() => onDeleteRole(role)} />
        </ButtonGroup>
```

Produces this alignment:
![image](https://user-images.githubusercontent.com/1675025/47226216-f475a400-d38d-11e8-9e3c-4f320fd3b55f.png)

With this HTML code:
![image](https://user-images.githubusercontent.com/1675025/47226266-10794580-d38e-11e8-9b09-33529bf668c4.png)

Note how one's a button and the other an 'a' ?!

**Comment by astanciu** [comment]
it's in development, not live yet... but you can check out the `authz-feature` branch of manage in vivaldi, then check out the Roles section

**Comment by astanciu** [comment]
https://github.com/auth0/manage/blob/authz-feature/src/modules/authz/roles/list/RolesList.js#L14

**Comment by Rupeshiya** [comment]
@astanciu  getting 404

**Comment by landitus** [comment]
Sorry @Rupeshiya but you won't be able to access this because it's part of a private repo. Mind that all hackoctoberfest issues are tagged with a 🎃. I believe all issues available are gone, but maybe we can tag some new ones for next week.

Sorry about that!
