### ISSUE TITLE
Inline Form with Stack has improper vertical alignment

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#1005]
**Describe the bug**
The way to implement an inline form right now is through a `Stack` component

![image](https://user-images.githubusercontent.com/1863771/47300236-a389d800-d639-11e8-9019-aa22fbbde464.png)

But the form elements are not aligned horizontally when there are errors in the form

**Expected behavior**
Form elements should horizontally align with each other.

This sounds like a great opportunity to introduce `<Form layout="inline"/>`

**Screenshots**

![image](https://user-images.githubusercontent.com/1863771/47299932-f57e2e00-d638-11e8-99d1-b62d16814097.png)

[💻 Playground link](https://auth0-cosmos.now.sh/docs/#/playground?code=/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20(%250A%20%20%20%20%3CForm%20layout=%22label-on-top%22%3E%250A%20%20%20%20%20%20%3CStack%20widths=%7B%5B45,%2045,%2010%5D%7D%3E%250A%20%20%20%20%20%20%20%20%3CForm.TextInput%250A%20%20%20%20%20%20%20%20%20%20label=%22Name%22%250A%20%20%20%20%20%20%20%20%20%20type=%22text%22%250A%20%20%20%20%20%20%20%20%20%20name=%22name%22%250A%20%20%20%20%20%20%20%20%20%20placeholder=%22read:appointment%22%250A%20%20%20%20%20%20%20%20%20%20error=%22whats%20up%22%250A%20%20%20%20%20%20%20%20/%3E%250A%20%20%20%20%20%20%20%20%3CForm.TextInput%250A%20%20%20%20%20%20%20%20%20%20label=%22Description%22%250A%20%20%20%20%20%20%20%20%20%20type=%22text%22%250A%20%20%20%20%20%20%20%20%20%20name=%22description%22%250A%20%20%20%20%20%20%20%20%20%20placeholder=%22Read%20your%20appointments%22%250A%20%20%20%20%20%20%20%20%20%20error=%22whats%20up%22%250A%20%20%20%20%20%20%20%20/%3E%250A%20%20%20%20%20%20%20%20%3CForm.Actions%250A%20%20%20%20%20%20%20%20%20%20primaryAction=%7B%7B%20label:%20%22Save%20Changes%22,%20handler:%20()%20=%3E%20%7B%7D%20%7D%7D%250A%20%20%20%20%20%20%20%20/%3E%250A%20%20%20%20%20%20%3C/Stack%3E%250A%20%20%20%20%3C/Form%3E%250A%20%20);%250A%7D;%250A%250Arender(Example);%250A)

**Cosmos version:**
0.6.0

**Comment by m4tr1k** [comment]
@siddharthkp Hi, I think I found a solution for that, but I need to test it first. I'm kind of new to Jest and I don't know how to use it well. I tried enter as guest on auth0 slack but I can't sign in. I think I need some help on that. If you could help me, I would be grateful. 

Thank you!

**Comment by rakhi2104** [comment]
The reason here looks like, the error messages push the form field a little bit up. While the button remains in the same place.

**Comment by m4tr1k** [comment]
@rakhi2104 What I did was if the `<Form.TextInput />` has a `error` prop, the margin-top of the button would be `${spacing.xxsmall}`, otherwise it would be `${spacing.large}`. The thing is that I can't test if this is correct and I don't know how to use Jest very well, so I would like some help on that.

**Comment by rakhi2104** [comment]
That sounds like a cool hack. Maybe someone could help you run some tests using Jest. I too am new to Jest and testing 😌

**Comment by m4tr1k** [comment]
I'll try my best 😃, I don't know if I'm able to PR without testing if I can't test my scripts through Jest...

**Comment by hzalaz** [comment]
It will be great if we can set the item vertical alignment, like in https://www.w3schools.com/csSref/css3_pr_align-self.asp, so I can specify `baseline` or `center`

**Comment by landitus** [comment]
Related to https://github.com/auth0/cosmos/issues/1113
