### ISSUE TITLE
The Logo Page in the docs, just turns everything blank.

### ISSUE THREAD

**Issue by DakshMiglani** [auth0/cosmos#104]
![peek 2017-12-29 20-52](https://user-images.githubusercontent.com/23355449/34440295-493841fa-ecda-11e7-9c83-627e8858849a.gif)

When I get to the Logo Page in docs, the docs go blank for some weird reason.

**Comment by DakshMiglani** [comment]
same happens in TextArea, ActionInput and Sidebar.

**Comment by siddharthkp** [comment]
fixed in https://github.com/auth0/cosmos/pull/114

**Comment by DakshMiglani** [comment]
Thank you :D
