### ISSUE TITLE
repeated 'name' attribute in Checkbox docs

### ISSUE THREAD

**Issue by rakhi2104** [auth0/cosmos#1042]
**Describe the bug**
In docs, the "name" attribute for the checkbox is repeated if the name value is user defined

**Expected behavior**
Replace the previous value of the "name" attribute.

**Screenshots**
![screenshot from 2018-10-28 17-23-02](https://user-images.githubusercontent.com/17671710/47615630-23e78780-dad7-11e8-9502-2ec958c05c0d.png)

**Comment by gutsytechster** [comment]
@rakhi2104 can I take up this issue?

**Comment by rakhi2104** [comment]
I'm actually working on this. :space_invader: 
Oops !

**Comment by gutsytechster** [comment]
Ok no problem :)

**Comment by rakhi2104** [comment]
@siddharthkp, the `name="example"` is in the checkbox.md which is being rendered on the playground. We need to do a specific workaround for this checkbox item. All other components, to my knowledge, are free of this bug.

**Comment by rakhi2104** [comment]
Found out that the `select` component also has the same problem
![screenshot from 2018-11-03 10-30-03](https://user-images.githubusercontent.com/17671710/47948260-9a5f0c00-df53-11e8-80d0-b23eaa6271b6.png)

**Comment by rakhi2104** [comment]
Really Cool !!!
Can I work on this?
