### ISSUE TITLE
Autocomplete plugin for editors

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#105]
An autocomplete plugin for code editors could be the most least frictional way of consuming cosmos

We've talked a lot about making the docs really good because that is where folks will find components and learn their usage.

The next step would be to start thinking about integrating the docs with people's workflow = IDEs, sketch, desktop app, etc are good places to explore

**Comment by nkohari** [comment]
I'm going to close this for now; we can capture it on the long-term roadmap.
