### ISSUE TITLE
Add disabled option to Select

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#1062]
We are missing a way to disabled options inside the Select component. This is a native feature to HTML.

**Comment by rakhi2104** [comment]
I did try adding the disable feature, but can't figure out a way to stylize the disabled select option.
There is hardly any noticeable difference between the disabled and the others.
Any suggestions?
![screenshot from 2018-11-03 13-08-29](https://user-images.githubusercontent.com/17671710/47949474-ab1a7c80-df69-11e8-8648-28a64f059e23.png)

**Comment by rakhi2104** [comment]
Noticed Select in sandbox fails to work for readonly mode. Jump [here](https://auth0-cosmos.now.sh/sandbox/?selectedKind=Select&selectedStory=readonly&full=0&addons=1&stories=1&panelRight=0)
