### ISSUE TITLE
Table throws Warning about Spinner

### ISSUE THREAD

**Issue by astanciu** [auth0/cosmos#1092]
The `Table` component throws this warning when using the `loading` prop

![image](https://user-images.githubusercontent.com/1675025/48723033-8c67e700-ebf3-11e8-8c8d-3f95642e9b0b.png)

**Comment by francocorreasosa** [comment]
Hey @astanciu, thank you for reporting this. I've already wrote a fix and it should be shipped on Cosmos' next release.
