### ISSUE TITLE
Label folds on to itself

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#1099]
**Describe the bug**

The label folks onto itself when there is too much content inside it. It looks strange and ugly. This might happen on smaller screens.

**Expected behavior**

> For the label, why not make them display:inline-block? We would allow them to wrap and create a box for them. Even if we add a white-space: nowrap to avoid wraping, they should still be an inline-block conntainer.
> – @andresgalante

**Screenshots**

![image](https://user-images.githubusercontent.com/1863771/48770487-5b9cb600-ecb6-11e8-9b64-9021bce29263.png)
![image](https://user-images.githubusercontent.com/1863771/48770489-60616a00-ecb6-11e8-8cbc-248d39caaa13.png)

**Cosmos version:**
0.7.2

**Comment by andresgalante** [comment]
Why not just make it `inline-block`?
