### ISSUE TITLE
 Docs: Radio example is broken in the Form Field documentation

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#1109]
**Describe the bug**
You can't select any of the options 

**Expected behavior**
... You should be able to?

**Screenshots**
![bug report](https://user-images.githubusercontent.com/1863771/48839491-9a4c7200-ed83-11e8-8ca9-7c7f23e88db3.gif)

**Cosmos version:**
0.7.2

**Additional context**
It's on multiple pages of the docs - Form + Form.Field

**Comment by jvelezpo** [comment]
Hello @siddharthkp i remember working on that not long ago and it is working as expected under https://auth0-cosmos.now.sh/docs/#/component/form-field

https://github.com/auth0/cosmos/pull/962

let me know if if more changes are needed, and i will be happy to work on them

**Comment by siddharthkp** [comment]
Fixed in https://github.com/auth0/cosmos/pull/962! ✨

**Comment by siddharthkp** [comment]
Hey @jvelezpo Just released it, forgot to tag this issue 😄
