### ISSUE TITLE
ResourceList.actions does not support `href` nor `target`

### ISSUE THREAD

**Issue by jcenturion** [auth0/cosmos#1128]
**Is your feature request related to a problem? Please describe.**

The try button in auth0 dashboard / db connections is a link. 

![image](https://user-images.githubusercontent.com/302314/48916021-73fc0480-ee5f-11e8-9448-21e0801c8e1c.png)

**Describe the solution you'd like**

Support all button properties. Cosmos `Button` supports `href` and `target`.

**Describe alternatives you've considered**
-

**Additional context**

https://github.com/auth0/cosmos/blob/master/core/components/molecules/resource-list/item/item.js#L83-L97

**Comment by francocorreasosa** [comment]
I think we should go ahead and support passing raw Buttons here. wdyt @jcenturion 	@landitus 	@siddharthkp 	?

**Comment by landitus** [comment]
I'm bringing this question as it's related to the actions of the Resource List/Tables. What if we had to support the `More` drop-down design? Is this related to this PR?

<img width="279" alt="screen shot 2018-11-27 at 17 09 23" src="https://user-images.githubusercontent.com/239215/49108556-3b956580-f267-11e8-88ea-602524f07bfb.png">
