### ISSUE TITLE
Typescript support/definitions not working

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#1131]
**Describe the bug**
I've heard from @hzalaz that the current implementation to support typescript is failing. @jcenturion gave us a head start, but we need to either own it or drop it.

**Expected behavior**
Let's check with our users, test it out and find a solution.

**Cosmos version:**
0.8.1

**Comment by francocorreasosa** [comment]
I'm actually working on this

**Comment by landitus** [comment]
Awesome!
