### ISSUE TITLE
flatmap-stream is currently in your dependency tree

### ISSUE THREAD

**Issue by HerrBertling** [auth0/cosmos#1144]
**Describe the bug**
You maybe heard about the issue with a [malicious package being installed via event-stream](https://github.com/dominictarr/event-stream/issues/116). I setup your project yesterday, heard of the issue today and saw that flatmap-stream is included in the dependency tree of this repo.

**Expected behavior**
The package `flatmap-stream` should not be installed when setting up this repo.

**Screenshots** (well, code :wink:)

```sh
$ yarn why flatmap-stream
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "flatmap-stream"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "flatmap-stream@0.1.1"
info Reasons this module exists
   - "_project_#if-env#npm-run-all#ps-tree#event-stream" depends on it
   - Hoisted from "_project_#if-env#npm-run-all#ps-tree#event-stream#flatmap-stream"
info Disk size without dependencies: "36KB"
info Disk size with unique dependencies: "36KB"
info Disk size with transitive dependencies: "36KB"
info Number of shared dependencies: 0
```

**Cosmos version:**
Since I just cloned the repo yesterday, it's version `0.8.1`.

**Additional context**
I went down the dependency tree and saw a note on the [if-env](https://github.com/ericclemmons/if-env) package that recommends using [per-env](https://github.com/ericclemmons/per-env) instead. That could probably solve this because per-env doesn't have any dependencies at all.

**Comment by francocorreasosa** [comment]
Thank you for the report, I’ll take care of this

**Comment by francocorreasosa** [comment]
It turns out we did not even using `if-env` right now. Easy fix, thanks.

**Comment by HerrBertling** [comment]
Ha, that's even better 👍 🚀
