### ISSUE TITLE
Heading component does not support h5

### ISSUE THREAD

**Issue by jcenturion** [auth0/cosmos#1148]
**Describe the bug**

There is no support for h5 in `Heading` component

**Expected behavior**

`Heading` supports h5.

**Screenshots**

![image](https://user-images.githubusercontent.com/302314/49099940-83a98d80-f251-11e8-82e5-5c18ac961594.png)

**Cosmos version:**

`0.8.1`

**Additional context**
-

**Comment by siddharthkp** [comment]
@landitus What's the font-size and font-weight for h5?

**Comment by jvelezpo** [comment]
I can jump on it if you tell me the `font-size` and `font-weight` for h5

FYI here are the size and weight for `h3` and `h4`

```
Heading.Element[3] = BaseHeading.withComponent('h3').extend`
  font-size: 18px; /* TO-DO: tokenize */
  font-weight: ${fonts.weight.bold};
`

Heading.Element[4] = BaseHeading.withComponent('h4').extend`
  font-size: 14px;
  font-weight: ${fonts.weight.medium};
`
````

**Comment by landitus** [comment]
Thanks @jvelezpo 	! We need to do a design for this issue first. You can check that this one is marked with the `design needed` tag, to note that we need a design spec first before jumping into code. 🙂
