### ISSUE TITLE
Image inside ResourceList Item should should be centered and scaled to content

### ISSUE THREAD

**Issue by hzalaz** [auth0/cosmos#1149]
**Describe the bug**
Using the ResourceList component the images are not scaled and centered to the image's container. Check the [folllowing link](http://auth0-manhattan.herokuapp.com/?selectedKind=Applications%7CList&selectedStory=list&full=0&addons=0&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Expected behavior**
I expect the Icon to be centered and sized to the content area it has in the item's row

**Screenshots**
<img width="875" alt="image" src="https://user-images.githubusercontent.com/895992/49100738-5827a280-f253-11e8-89a9-99dfaeca5a55.png">

**Cosmos version:**
v0.8.1

**Additional context**

**Comment by landitus** [comment]
Thanks for reporting! I'm sending you new images for this situation since the Avatar container of the Resource List is padding-less, to be able to support any kind of image image.

**Comment by landitus** [comment]
Most of the time, the designer of the avatar/image decides the padding within the image, as it’s kind of an optical thing. This is why the container is padding-less. Also, if the image has a background, we would create an undesired border around the image.

I'm closing this issue and moving on to testing different aspect ratios and size fitting for Image and Avatar in https://github.com/auth0/cosmos/issues/1150
