### ISSUE TITLE
Image is not scaled down to content 

### ISSUE THREAD

**Issue by hzalaz** [auth0/cosmos#1150]
**Describe the bug**
A bigger image inside the `Image` container, wont be scaled down if it does not fit.

**Expected behavior**
To be scaled down, or at least make me choose the rendering option like `scaleAspectFit` or `center` or `top`. (Here is an example of how iOS does it https://developer.apple.com/documentation/uikit/uiview/contentmode)

**Screenshots**
<img width="769" alt="image" src="https://user-images.githubusercontent.com/895992/49101047-092e3d00-f254-11e8-9d12-47b20ff2fa6a.png">

**Cosmos version:**
v0.8.1

**Additional context**
Our storybook is [here](http://auth0-manhattan.herokuapp.com/?selectedKind=Applications%7CCreation&selectedStory=form&full=0&addons=0&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by hzalaz** [comment]
Might be good to try https://caniuse.com/#feat=object-fit since @vctrfrnndz achieved his goal of dropping IE 11

**Comment by andresgalante** [comment]
@hzalaz I am working on this one.

[object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)'s values are: `fill | contain | cover | none | scale-down`

Would those be enough for your needs or would you like to see all the values described on the iOS specs too?

For example `top`, `center`, `top-right` etc?
