### ISSUE TITLE
Form.Actions - Allow passing button props

### ISSUE THREAD

**Issue by cristiandouce** [auth0/cosmos#1163]
**Describe the bug**
In order to better control the submit flow we need to be able to fully customize the type of buttons used in forms. As it's recommended from cosmos to use `Form.Actions` it'd ideal that:

1. We could customize the `type` attribute of the actions
2. That secondary actions (buttons) have type "button" by default.

**Expected behavior**
When the button is type `submit` the control of the form submission passes through it's state. So, if for example the button is disabled, the whole form is disabled from submission.

https://codepen.io/anon/pen/MzPGKj

**Screenshots**
Check the CodePen above.

**Cosmos version:**
`0.8.1`

**Additional context**
It's crucial for application flow control.

**Comment by siddharthkp** [comment]
Hey! @cristiandouce,

> 1. We could customize the type attribute of the actions

You can pass a `type` attribute in the action object and it will passed to the button (disabled as well)

[Here's an example](https://auth0-cosmos.now.sh/docs/#/playground?code=%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20(%250A%20%20%20%20%3CForm%3E%20%250A%20%20%20%20%20%20%3CForm.TextInput%20label=%22Field%20label%22%20type=%22text%22%20placeholder=%22Enter%20something%22%20/%3E%250A%20%20%20%20%20%20%3CForm.Actions%20%250A%20%20%20%20%20%20%20%20primaryAction=%7B%7B%20label:%20'Save',%20type:'submit',%20disabled:%20true,%20handler:%20()%20=%3E%20%7B%20alert(1)%20%7D%20%7D%7D%20%250A%20%20%20%20%20%20%20%20secondaryActions=%7B%5B%7B%20label:%20'Clear',%20type:'button',%20handler:%20()%20=%3E%20%7B%20alert(2)%20%7D%20%7D%5D%7D%250A%20%20%20%20%20%20/%3E%250A%20%20%20%20%3C/Form%3E%250A%20%20)%250A%7D%250A%250Arender(Example)%250A)

2. That secondary actions (buttons) have type "button" by default.

Good catch! That's definitely a bug! 

The workaround if you're in a hurry is to pass it yourself ([see example](https://auth0-cosmos.now.sh/docs/#/playground?code=%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20(%250A%20%20%20%20%3CForm%3E%20%250A%20%20%20%20%20%20%3CForm.TextInput%20label=%22Field%20label%22%20type=%22text%22%20placeholder=%22Enter%20something%22%20/%3E%250A%20%20%20%20%20%20%3CForm.Actions%20%250A%20%20%20%20%20%20%20%20primaryAction=%7B%7B%20label:%20'Save',%20type:'submit',%20disabled:%20true,%20handler:%20()%20=%3E%20%7B%20alert(1)%20%7D%20%7D%7D%20%250A%20%20%20%20%20%20%20%20secondaryActions=%7B%5B%7B%20label:%20'Clear',%20type:'button',%20handler:%20()%20=%3E%20%7B%20alert(2)%20%7D%20%7D%5D%7D%250A%20%20%20%20%20%20/%3E%250A%20%20%20%20%3C/Form%3E%250A%20%20)%250A%7D%250A%250Arender(Example)%250A))
