### ISSUE TITLE
Button with href inner layout is broken

### ISSUE THREAD

**Issue by hzalaz** [auth0/cosmos#1164]
**Describe the bug**
When using `href` for `Button` the icon and container does not keep the same appearance when not using `href`

**Expected behavior**
To have the same layout without `href`

**Screenshots**
 `Check link to playgrounds`

**Cosmos version:**
v0.8.1

**Additional context**

- [Example alone](https://auth0-cosmos.now.sh/docs/#/playground?code=%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20(%250A%20%20%3CButton%20appearance=%22default%22%20icon=%22emails%22%20href=%22https://dus.com%22%20/%3E)%250A%7D%250A%250Arender(Example)%250A
)
- [Example inside table column](https://auth0-cosmos.now.sh/docs/#/playground?code=%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20(%250A%20%20%3CTable%250A%20%20items=%7B%5B%250A%20%20%20%20%7B%250A%20%20%20%20%20%20name:%20'Harry%20Kane',%250A%20%20%20%20%20%20goals:%206,%250A%20%20%20%20%20%20assists:%200,%250A%20%20%20%20%20%20country:%20'%F0%9F%87%AC%F0%9F%87%A7',%250A%20%20%20%20%20%20image:%20'https://twitter-avatar.now.sh/HKane'%250A%20%20%20%20%7D,%250A%20%20%20%20%7B%250A%20%20%20%20%20%20name:%20'Romelu%20Lukaku',%250A%20%20%20%20%20%20goals:%204,%250A%20%20%20%20%20%20assists:%201,%250A%20%20%20%20%20%20country:%20'%F0%9F%87%A7%F0%9F%87%AA',%250A%20%20%20%20%20%20image:%20'https://twitter-avatar.now.sh/Romelu_lukaku9'%250A%20%20%20%20%7D,%250A%20%20%20%20%7B%250A%20%20%20%20%20%20name:%20'Antoine%20Griezmann',%250A%20%20%20%20%20%20goals:%204,%250A%20%20%20%20%20%20assists:%202,%250A%20%20%20%20%20%20country:%20'%F0%9F%87%AB%F0%9F%87%B7',%250A%20%20%20%20%20%20image:%20'https://twitter-avatar.now.sh/AntoGriezmann'%250A%20%20%20%20%7D,%250A%20%20%20%20%7B%250A%20%20%20%20%20%20name:%20'Ivan%20Peri%C5%A1i%C4%87',%250A%20%20%20%20%20%20goals:%203,%250A%20%20%20%20%20%20assists:%201,%250A%20%20%20%20%20%20country:%20'%F0%9F%87%AD%F0%9F%87%B7',%250A%20%20%20%20%20%20image:%20'https://twitter-avatar.now.sh/ivanperisic44'%250A%20%20%20%20%7D%250A%20%20%5D%7D%250A%20%20onRowClick=%7B(evt,%20item)%20=%3E%20alert(%60$%7Bitem.name%7D%20was%20clicked!%60)%7D%250A%3E%250A%20%20%3CTable.Column%20field=%22name%22%20title=%22Name%22%20width=%2230%25%22%3E%250A%20%20%20%20%7Bitem%20=%3E%20%3CAvatarBlock%20type=%22user%22%20image=%7Bitem.image%7D%20title=%7Bitem.name%7D%20size=%22compact%22%20/%3E%7D%250A%20%20%3C/Table.Column%3E%250A%20%20%3CTable.Column%20field=%22country%22%20title=%22Country%22%20/%3E%250A%20%20%3CTable.Column%20field=%22goals%22%20title=%22Goals%22%20/%3E%250A%20%20%3CTable.Column%20field=%22assists%22%20title=%22Assists%22%20width=%225%25%22%3E%7B(item)%20=%3E%20(%3CButton%20appearance=%22default%22%20icon=%22emails%22%20href=%22https://dus.com%22%20/%3E)%7D%3C/Table.Column%3E%250A%3C/Table%3E)%250A%7D%250A%250Arender(Example)%250A)

**Comment by landitus** [comment]
While we fix this one, I think it's a good idea to add test case for Button and Icon buttomn with link with the link prop:

```jsx
<Stack>
	<Button>Button</Button>
	<Button href="https://auth0.com">Link</Button>
	<Button icon="copy"/>
	<Button icon="copy" href="https://auth0.com" />href="https://auth0.com">Link</Button>
<Stack>
```

**Comment by siddharthkp** [comment]
Did some digging:

Seems like the bug is in the case with href

![image](https://user-images.githubusercontent.com/1863771/49205352-c778d000-f3d4-11e8-8f0d-aad723622d77.png)

**Comment by siddharthkp** [comment]
Exchanging https://github.com/auth0/cosmos/issues/1164 with @francocorreasosa because he has more info about this one.

@francocorreasosa It looks like type Link uses `display: table` but the default one doesn't

**Comment by andresgalante** [comment]
@siddharthkp 👍 it's set to be a `table` element and it's causing the issue. 

I'll work on this issue as soon as I can

**Comment by siddharthkp** [comment]
Thanks @hzalaz for providing the playground examples, it helped in triaging the bug super fast 💯
