### ISSUE TITLE
Text Component

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#120]
<img width="702" alt="screen shot 2018-01-04 at 16 53 02" src="https://user-images.githubusercontent.com/1576/34581704-745744ec-f15f-11e7-8e0d-1bc79b402634.png">

**Comment by landitus** [comment]
Should we call it Paragraph?

**Comment by nkohari** [comment]
We may want both a `<Text>` and a `<TextBlock>` (or `<Paragraph>`) component. The former representing a styled `<span>`, and the latter representing a styled `<p>`.
