### ISSUE TITLE
Specify deprecation replacements on Alert docs

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#1211]
Example: https://auth0-cosmos.now.sh/docs/#/component/alert

We are telling the `text` prop is deprecated but we're not detailing the replacement. (We should explain the text is now passed as children)

**Comment by landitus** [comment]
Should we do a pass across all components to check deprecations have a detailed replacement?

**Comment by landitus** [comment]
Would this include deprecation alerts on the console as well?

**Comment by landitus** [comment]
Related to https://github.com/auth0/cosmos/issues/1277
