### ISSUE TITLE
Playground erases all page

### ISSUE THREAD

**Issue by m4tr1k** [auth0/cosmos#1216]
I'm always in touch with this repo, and I like a lot what you are doing, hope that one day I could help you on another issue! But first take a look at this one.

**Describe the bug**
If you go to Playground (on cosmos website) and erase `Example` on `render(Example)`, the whole page is erased, I need to refresh the website to go to Playground again and navigate the website.

**Expected behavior**
Give an error on preview

**Screenshots**
Erase what's highlighted to see what's happening
![capturar](https://user-images.githubusercontent.com/12871065/49469841-74ea4a00-f800-11e8-8f78-3dfc795c740f.PNG)

**Cosmos version:**
0.93

**Comment by francocorreasosa** [comment]
Hi @m4tr1k! Thank you for the words, it means a lot :) 

Also thank you for reporting this, as I can see the React Invariant 152 is raised and the whole app breaks. We should catch that in the container.

https://reactjs.org/docs/error-decoder.html/?invariant=152&args[]=r

**Comment by cliffpyles** [comment]
@francocorreasosa Care if I take a shot at this one? Were you thinking it should be caught with `componentDidCatch` in `playground.js`?

https://github.com/auth0/cosmos/blob/master/internal/docs/playground.js
