### ISSUE TITLE
No margin at the bottom of Dialog in Firefox

### ISSUE THREAD

**Issue by hzalaz** [auth0/cosmos#1217]
**Describe the bug**
No bottom padding at the bottom of a scrollable alert in Firefox

**Expected behavior**
To look the same as in Chrome

**Screenshots**

In Firefox
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/895992/49487277-6ca20700-f820-11e8-8929-1fb670a591dd.png">

In Chrome
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/895992/49487321-9ce9a580-f820-11e8-9b80-0c85bba2d4f0.png">

**Cosmos version:**
v0.9.x

**Additional context**
N/A

**Comment by andresgalante** [comment]
@hzalaz I can't reproduce it on Cosmos docs, Do you have a URL where I can test it?

What version of FF are you on?

**Comment by francocorreasosa** [comment]
Is this still happening @hzalaz @andresgalante ?

**Comment by francocorreasosa** [comment]
It seems yes
![imagen](https://user-images.githubusercontent.com/4152942/51270712-6ae16c80-19a4-11e9-90c1-755dafa4c209.png)

http://auth0-manhattan.herokuapp.com/?selectedKind=Applications%7CDetails%20-%20Addons&selectedStory=firebase%20-%20settings%20-%20sdk%20v2&full=0&addons=0&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by landitus** [comment]
Yes, let me give context on this usecase, it's a bit tricky.
