### ISSUE TITLE
Deprecations throw full screen on development

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#1222]
We recently deprecated passing actions as objects in the ResouceList component. Now everytime I go to the ResourceList page in docs (dev mode), that incompatibility throws in full screen.

![image](https://user-images.githubusercontent.com/4152942/49536649-cf89b180-f8a5-11e8-93cc-77983341cfde.png)

**Comment by siddharthkp** [comment]
I'm guessing this doesn't exist on `0.10.1`?
