### ISSUE TITLE
Dialogs does not automatically close if I click below it.

### ISSUE THREAD

**Issue by jcenturion** [auth0/cosmos#1224]
**Describe the bug**
If I click on left, on right or above the dialog automatically closes. However, If I click below the dialog is not being closed.

**Expected behavior**
It should automatically close the dialog when clicking below it.

**Screenshots**

![image](https://user-images.githubusercontent.com/302314/49557329-14353d00-f8e6-11e8-84b7-fccca3f26001.png)

**Cosmos version:**
`0.9.3`

**Comment by francocorreasosa** [comment]
Hey! Thanks for the report. We will take a look at this.
