### ISSUE TITLE
PageHeader component renders empty div

### ISSUE THREAD

**Issue by astanciu** [auth0/cosmos#1226]
If the PageHeader component is used without any `actions` defined it will render an empty div.

```jsx
<PageHeader title="Multi-factor Authentication" />
```

results in:
```html
<div class="sc-esOvli jXQUTq" data-cosmos-key="page-header">
  <div class="sc-kgoBCf kkDVDp" data-cosmos-key="button-group"></div>  <- Here
  <h1 class="sc-brqgnP gIdlSI" size="1">Multi-factor Authentication</h1>
</div>
```

**Comment by landitus** [comment]
Adding a similar bug found in this example: https://auth0-cosmos.now.sh/sandbox/?selectedKind=Page%20Header&selectedStory=no%20description&full=0&addons=1&stories=1&panelRight=0

When no description is found, we still have the margin created by the grid.

<img width="1002" alt="screen shot 2018-12-11 at 14 51 24" src="https://user-images.githubusercontent.com/239215/49819467-45819300-fd54-11e8-8f32-f414b170eef7.png">
