### ISSUE TITLE
Define names of global tokens

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#1235]
The theming system within cosmos has 2 layouts, global and component variables.

To start setting it up, we should create a list of global variables with its values. This list will be the base and toolbox for later on implementing component variables.

These variables should define everything related to:

- Colors
- Spaces
- Shadows
- Typography
- Borders
- Breakpoints

but nothing related to any specific component.

This is an example:
https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/scss-variables.scss

## Units

Since we are defining units, this is a great time to change from px to rems! (easily done with a px to rem converter)

**Comment by andresgalante** [comment]
@landitus You'll find the list to fill out here:
https://github.com/auth0/cosmos/blob/tokens-system/core/tokens/global.js

and swatches here:
https://github.com/auth0/cosmos/blob/tokens-system/core/tokens/swatches.js

remember at this point we don't need it to be perfect, we just need something to keep the wheels going.
