### ISSUE TITLE
Add test to check each component has an automation attribute at the parent node

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#1239]
We need to ensure each one of our components has at least one automation attribute exposed at the parent / wrapper node.

**Comment by landitus** [comment]
Should we also check for the internal attributes as well? I guess we could test them so we don’t break any of our users tests

**Comment by francocorreasosa** [comment]
We are already doing that :) This test would be to check every component we expose has at least the automation attribute at its parent. Mostly for new components, rewrites, etc...

**Comment by landitus** [comment]
Perfect!
