### ISSUE TITLE
Text Area Input Component

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#126]
Like `<textarea>`. Similar to #125, but multi-line.

![screen shot 2018-01-04 at 12 25 39 pm](https://user-images.githubusercontent.com/1576/34575955-6327b2a2-f14a-11e7-8ba7-fea190a421b0.png)

**Comment by landitus** [comment]
Just an idea: would be interesting to support auto-growing the textarea to fit content, instead of the native resizing.
