### ISSUE TITLE
Tooltips render behind checkboxes

### ISSUE THREAD

**Issue by jcenturion** [auth0/cosmos#1307]
**Describe the bug**

The tooltip renders behind the checkbox.

**Expected behavior**

The tooltip renders correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/302314/50186303-31600780-02f9-11e9-8f62-3d62f2d37b25.png)

**Cosmos version:**

`0.10.1`

**Additional context**

https://auth0-cosmos-0-10-1.now.sh/docs/#/playground?code=%20%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250Aconst%20Example%20=%20()%20=%3E%20%7B%20%20return%20(%20%20%3Cdiv%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CCheckbox%20%20%20%20%20%20%20%20%20%20readOnly=%7Btrue%7D%20%20%20%20%20%20%20%20%20%20name=%22example%22%20%20%20%20%20%20%20%20%20%20value=%22one%22%20%20%20%20%20%20%20%20%20%20checked=%7Btrue%7D%20%20%20%20%20%20%20%20%20%20align=%22vertical%22%20%20%20%20%20%20%20%20%3E%20%20%20%20%20%20%20%20%20%20Basic%20Profile%20%20%20%20%20%20%20%20%3C/Checkbox%3E%20%20%20%20%20%20%20%20%3CTooltip%20content=%22Email%20and%20verified%20email%20flag%22%20position=%22right%22%3E%20%20%20%20%20%20%20%20%20%20%3CIcon%20name=%22help%22%20size=%2215%22%20color=%22default%22%20/%3E%20%20%20%20%20%20%20%20%3C/Tooltip%3E%20%20%20%20%20%20%20%20%20%20%20%20%3CCheckbox%20%20%20%20%20%20%20%20readOnly=%7Btrue%7D%20%20%20%20%20%20%20%20name=%22example%22%20%20%20%20%20%20%20%20value=%22one%22%20%20%20%20%20%20%20%20checked=%7Btrue%7D%20%20%20%20%20%20%20%20align=%22vertical%22%20%20%20%20%20%20%3E%20%20%20%20%20%20%20%20Extended%20Profile%20%20%20%20%20%20%3C/Checkbox%3E%20%20%3C/div%3E%20%20)%7D%250Arender(Example)%20%250A

**Comment by andresgalante** [comment]
@jcenturion thanks for reporting this bug. We are considering using [popper](https://popper.js.org/) to handle tooltips.

In the meantime, can you use a top aligned tooltip?
