### ISSUE TITLE
Replace use of random id

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#1310]
**Describe the bug**
We do an (over) smart thing in cosmos, we generate ids and labels to create relation between children inside a components

Example: Between a form label and form field (for + id attributes)

Because we don't have enough context about the components, we generate a random key on the fly. This works well for the user but is a pain to use in snapshots (because they change without change in the component)

**Expected behavior**
Attributes should be the same every time. 

~We should just ask the developer as a prop instead of trying to make this work behind the scenes.~

Found an alternative way which ensures the same id as long as the environment doesn't change: https://github.com/auth0/cosmos/pull/1374

**Cosmos version:**
0.11.0

**Additional context**
Reported here: https://github.com/auth0/cosmos/issues/1267 and https://github.com/auth0/cosmos/issues/1268

**Comment by landitus** [comment]
Should we close this @siddharthkp 	?
