### ISSUE TITLE
Implement tokens system v2

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#1359]
Maybe this is related to #479, as we a v2 version of the tokens that will coexist with the current token systems.

The next step after defining the new tokens is testing them inside components.

**Comment by siddharthkp** [comment]
There you go https://github.com/auth0/cosmos/pull/1431

**Comment by landitus** [comment]
Thanks @siddharthkp 	!!

**Comment by francocorreasosa** [comment]
@siddharthkp @landitus Does #1431 merge close this?

**Comment by siddharthkp** [comment]
Nope this is the giant task of actually building out the tokens 😓
