### ISSUE TITLE
Form.Radio - alignment bug

### ISSUE THREAD

**Issue by astanciu** [auth0/cosmos#1380]
**Describe the bug**
When using a <Form.Radio> component with at least 2 options, the radio buttons are not align in horizontal mode:

![image](https://user-images.githubusercontent.com/1675025/50664114-fc4ee880-0f79-11e9-8617-cc0b131bdadb.png)

```jsx
       <Form.Radio
          label="SMS Source"
          name="sms-source"
          selected="one"
          onChange={controller.smsSourceChange}
          align="horizontal"
        >
          <Radio.Option value="one">Use Copilot</Radio.Option>
          <Radio.Option value="two">Use From</Radio.Option>
        </Form.Radio>
```

The css for <label> has a 
```css
.ioYtLw .sc-dVhcbM:last-child {
    margin: 0;
}
```
which prob shouldn't be there if align=horizontal

**Comment by landitus** [comment]
@astanciu I cannot reproduce this in [0.11.0](https://auth0-cosmos-0-11-0.now.sh/docs/#/playground?code=/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20(%250A%20%20%20%20%3CForm%3E%250A%20%20%20%20%20%20%3CForm.Radio%20%20%20%20%20%20%20%20%20%20%250A%20%20%20%20%20%20%20%20%20%20label=%22SMS%20Source%22%20%20%20%20%20%20%20%20%20%20%250A%20%20%20%20%20%20%20%20%20%20name=%22sms-source%22%250A%20%20%20%20%20%20%20%20%20%20selected=%22one%22%250A%20%20%20%20%20%20%20%20%20%20align=%22horizontal%22%250A%20%20%20%20%20%20%20%20%3E%250A%20%20%20%20%20%20%20%20%20%20%3CRadio.Option%20value=%22one%22%3EUse%20Copilot%3C/Radio.Option%3E%250A%20%20%20%20%20%20%20%20%20%20%3CRadio.Option%20value=%22two%22%3EUse%20From%3C/Radio.Option%3E%250A%20%20%20%20%20%20%20%20%3C/Form.Radio%3E%20%20%250A%20%20%3C/Form%3E%250A%20%20%20%20)%250A%20%20%20%20%250A%250A%20%20%20%20%250A%7D%250A%250Arender(Example)%250A%250A) or [0.12.2](https://auth0-cosmos.now.sh/docs/#/playground?code=%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20(%250A%20%20%20%20%3CForm%3E%250A%20%20%20%20%20%20%3CForm.Radio%20%20%20%20%20%20%20%20%20%20%250A%20%20%20%20%20%20%20%20%20%20label=%22SMS%20Source%22%20%20%20%20%20%20%20%20%20%20%250A%20%20%20%20%20%20%20%20%20%20name=%22sms-source%22%250A%20%20%20%20%20%20%20%20%20%20selected=%22one%22%250A%20%20%20%20%20%20%20%20%20%20align=%22horizontal%22%250A%20%20%20%20%20%20%20%20%3E%250A%20%20%20%20%20%20%20%20%20%20%3CRadio.Option%20value=%22one%22%3EUse%20Copilot%3C/Radio.Option%3E%250A%20%20%20%20%20%20%20%20%20%20%3CRadio.Option%20value=%22two%22%3EUse%20From%3C/Radio.Option%3E%250A%20%20%20%20%20%20%20%20%3C/Form.Radio%3E%20%20%250A%20%20%3C/Form%3E%250A%20%20%20%20)%250A%20%20%20%20%250A%250A%20%20%20%20%250A%7D%250A%250Arender(Example)%250A) or in 

Can you confirm if this is fixed?

**Comment by landitus** [comment]
Upon debugging this, we see that the CSS can be improved. But the issue that is causing the misalignment is actually from styles coming from an external source in the app. We'll review this component, so that it's in better shape, but there's the need to take care of those external styles so that they don't step over the component.

**Comment by landitus** [comment]
Closing this as it was solved from the application's side
