### ISSUE TITLE
Detail page won't load in Manage demo

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#1385]
**Describe the bug**
Can't get to the Application detail page anymore. I go to https://auth0-cosmos.now.sh/manage/#/applications/apXVn76xBT7WougWj17MGXHSthfrBB and I still see the Applications page. I think many routes are failing from the sidebar as well. Looks like a bug.

**Comment by francocorreasosa** [comment]
This is working now.

https://auth0-cosmos.now.sh/manage/#/applications/apXVn76xBT7WougWj17MGXHSthfrBB
