### ISSUE TITLE
Deprecation of Resource List

### ISSUE THREAD

**Issue by andresgalante** [auth0/cosmos#1389]
As we create the [new list](https://github.com/auth0/cosmos/pull/1364) that supports a structure for a resource list too, it's time to think of how to deprecate the widely used Recourse List Component.

## The problem

Since resource list is been used on lots of Manhattan screens, by removing it we'd be creating a steeper upgrade path to v1.

We really want authors to migrate since v1 will remove margins on components allowing correct use of the layout system.

## The idea

I think we should keep the old Resource list component for a while with some warnings:

- Add a console deprecation warning pointing to use the new list
- Add a noticeable depreciation alert at the top of the doc so nobody else uses it.

## Why would authors upgrade?

The old resource list will not get new features like selectable (checkboxes) or expansion.

If an author needs a new feature and they are on the old recourse list, they must upgrade to the new list.

Plus, warnings a pretty annoying to see.

@siddharthkp @francocorreasosa @landitus what do you think?

**Comment by francocorreasosa** [comment]
Sounds good, although I would not completely hide the current Resource List from the docs but include it as deprecated and put a warning. This way we can keep providing docs for folks that cannot migrate to the new List at the moment.

**Comment by andresgalante** [comment]
@francocorreasosa Sounds good, I'll change:

> Keep it hidden from the docs, or width a noticeable depreciation alert at the top of the doc so nobody else uses it.

to 

> Add a noticeable depreciation alert at the top of the doc so nobody else uses it.

**Comment by siddharthkp** [comment]
> If an author needs a new feature and they are on the old recourse list, they must upgrade to the new list.

Sounds fair.

Let's do this
