### ISSUE TITLE
Deprecation of Stack

### ISSUE THREAD

**Issue by andresgalante** [auth0/cosmos#1390]
As we create the new StackLayout, it's time to think of how to deprecate the widely used Stack Component.

## The problem

Since Stack is been used on lots of Manhattan screens, and internal cosmos components by removing it we'd be creating a steeper upgrade path to v1.

We really want authors to migrate since v1 will remove margins on components allowing correct use of the layout system.

## The idea

First, we'd have to change all our internal uses of Stack to Stack layout and make sure StackLayout has all the features we need.

As far as external uses of Stack I think we should keep it for a while with some warnings:

- Add a console deprecation warning pointing to use the StackLayout
- Add a noticeable depreciation alert at the top of the doc so nobody else uses it.

## Why would authors upgrade?

Mainly because of the warnings, but also the old Stack is a bit unpredictable and not as flexible as it should be.

@siddharthkp @francocorreasosa @landitus what do you think?

**Comment by francocorreasosa** [comment]
Sounds good! 💯

**Comment by siddharthkp** [comment]
Sounds very reasonable: `Stack -> StackLayout`

co-signed 😋
