### ISSUE TITLE
Heading Components

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#140]
Like `<h1>`, `<h2>`, etc.

<img width="407" alt="screen shot 2018-01-04 at 23 29 36" src="https://user-images.githubusercontent.com/239215/34593046-30e5ff8a-f1a7-11e7-95b0-d52167935cbe.png">

**Comment by landitus** [comment]
I've reviewed the design of the heading component and fixed a few things:

- Weights are consistent with our app
- We currently have only 3 sizes, so I've removed the rest

The rest of the sizes belong to the typography scale and could be encoded in tokens.
