### ISSUE TITLE
Form Helper Text Component

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#142]
![screen shot 2018-01-04 at 12 54 04 pm](https://user-images.githubusercontent.com/1576/34577224-66cbfa7c-f14e-11e7-8756-5286a793e401.png)

This component should support **bold**, **code** and **links**.

**Comment by landitus** [comment]
When trying to output the following:

```
Comma-separated list of allowed origins for use with Cross-Origin Authentication and web message response mode, in the form of 
<scheme> "://" <host> [ ":" <port> ], such as 
https://login.mydomain.com or http://localhost:3000.
```
 I get a JSX errors. 

> Expected corresponding JSX closing tag for <host> 

Is there a way to escape these tags?
