### ISSUE TITLE
[DXDP-79] [Layouts] Test the Layout System on Manhattan

### ISSUE THREAD

**Issue by andresgalante** [auth0/cosmos#1425]
We've already proved and tested that Layouts allow correct alignment and spacing of components.

But we are unsure if the gutters we've defined can cope with the use cases presented on Manage.

That's why we've like to go into Manhattan and test on 3 or 4 pages samples, removing all margins that have been set manually and introducing Cosmos Layouts and the margin prop to align things correctly.

Cosmos' layouts should be adjusted if needed.

As a byproduct of this exercise, we'll create a demo/template for the Manhattan team to follow when they decide to migrate to Cosmos v1 that will have no margins on components. (#1395)

The result of this test is:
- A fix to Cosmos' layout system if needed.
- A PR to Manhattan
- A demo of how Layouts works

To be done after #1421

**Comment by francocorreasosa** [comment]
Closed by DXDP-79
