### ISSUE TITLE
App Header Component

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#143]
![screen shot 2018-01-04 at 1 58 59 pm](https://user-images.githubusercontent.com/1576/34579546-6dbd42ce-f157-11e7-8e44-460d872fdf8c.png)

**Comment by landitus** [comment]
The App Header could be mocked at first. It's more to make the mockup more "real". At a latter stage we can look at an API to accomplish this. @beneliflo has experience with headers :)
