### ISSUE TITLE
It would be nice to have SSR Support

### ISSUE THREAD

**Issue by davesnx** [auth0/cosmos#1430]
**Describe the bug**
cosmos relies on window.document to be present, making SSR impossible.

**Expected behavior**
Don't do anything when there's no `document` present.

**Additional context**
I'm not pretty sure if it's in the roadmap, but it's a straight forward "feature" to have in a design system. Implementation-wise it woudn't take too much time to add a check if it exist and do anything on any case. I'm not sure if this would affect in any way the reset that you add at runtime.

As a personal example I wanted to try to create some UI with `Next` and it's not possible to use any component.

**Comment by davesnx** [comment]
If there's not an issue, I'm happy to create a PR :D

**Comment by francocorreasosa** [comment]
Hey @davesnx! Thanks for your report. We're always open to external contributions, so go ahead :)

=======

Duplicate of #971

**Comment by francocorreasosa** [comment]
Closing as duplicate of #971
