### ISSUE TITLE
Checkbox visually breaks when label is long

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#1461]
**Describe the bug**
When you stress out the Checkbox, the component visually breaks

**Expected behavior**
The checkbox would handle any text size and create proper indentation so the text never goes below the checkbox square.

Let's add proper testing as well. 

**Screenshots**

Rendered code:
![screen shot 2019-01-25 at 19 20 16](https://user-images.githubusercontent.com/239215/51776140-cadbbf80-20d6-11e9-9d69-8ce5d57e1e4b.png)

Visual reference:
<img width="792" alt="screen shot 2019-01-25 at 19 28 19" src="https://user-images.githubusercontent.com/239215/51776315-74bb4c00-20d7-11e9-92ad-fd34b9e6fdda.png">

**Cosmos version:**
0.14

**Comment by m4tr1k** [comment]
Hi @landitus! I think I found a solution for that. Can I do a PR?
Thank you 😄

**Comment by landitus** [comment]
Yes, go ahead @m4tr1k !

**Comment by landitus** [comment]
Thanks @m4tr1k !!

**Comment by francocorreasosa** [comment]
Fixed in a026549
