### ISSUE TITLE
Popup Image

### ISSUE THREAD

**Issue by m4tr1k** [auth0/cosmos#1465]
**Describe the solution you'd like**
I think it would be a nice idea to add an optional feature to the image component like the popup:

![sem titulo](https://user-images.githubusercontent.com/12871065/51939386-3e4b3d00-2407-11e9-9ae1-8f150bb6e876.png)

I'm not saying to do just like this, it's just to show what I was thinking.

**Additional context**
On specific images, have an optional prop that triggers this (and a caption too, it would be interesting).

Let me know what you think, thank you!

**Comment by andresgalante** [comment]
Hi Francisco, I think this is a good idea. But since it's not a common usecase, what stops an author to compose it with a dialog width an image inside?

**Comment by m4tr1k** [comment]
Hi, I didn't understand exactly what you are trying to say... Do you mean if someone puts an image on a dialog component?

**Comment by francocorreasosa** [comment]
@m4tr1k Something like this: http://bit.ly/cosmos-playground-dialog-with-image (with some additional CSS tweaks)

**Comment by m4tr1k** [comment]
@francocorreasosa Yeah something like that could work, but I think it makes more sense to click on the image to expand it, for example in a image gallery, and have some arrows to navigate to different images
Do you understand my idea?

**Comment by francocorreasosa** [comment]
I get it, yeah. But I'm not sure if that should be part of cosmos at the moment, to me sounds more like application-specific code.

**Comment by m4tr1k** [comment]
Of course, no problem! Hope to help you more on the project!

**Comment by francocorreasosa** [comment]
Sure thing! :) Thank you for all your contributions!
