### ISSUE TITLE
Checkbox group is not documented

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#1502]
**Is your feature request related to a problem? Please describe.**
Checkbox group is not documented

**Describe the solution you'd like**
Add examples and documentation in Docs

**Comment by MateoKruk** [comment]
It's already done: https://auth0-cosmos.now.sh/docs/#/component/checkbox

**Comment by loginist** [comment]
Thank you for letting us know. If you feel you can improve on the existing documentation, please feel free to send a PR 😄
