### ISSUE TITLE
Documentation: Select component's doc has duplicate options props

### ISSUE THREAD

**Issue by ubenzer** [auth0/cosmos#1542]
**Describe the bug**
Please see the screenshot. Two `options` are shown in the doc.

**Expected behavior**
Only one `options` is shown in the docs.

**Screenshots**
![](https://user-images.githubusercontent.com/396400/53965257-22ffdb80-40f1-11e9-86b4-655c197001e9.png)

**Cosmos version:**
0.19.0

**Additional context**
N/A

**Comment by landitus** [comment]
Done !

**Comment by francocorreasosa** [comment]
We have not fixed this

**Comment by landitus** [comment]
ups!

**Comment by cliffpyles** [comment]
Hi @francocorreasosa @landitus ! This is my first contribution to the project, and this one seemed like it was pretty straightforward. Let me know if I need to make any other changes though.
