### ISSUE TITLE
Feature request: Make changeHandlers return the value as well

### ISSUE THREAD

**Issue by astanciu** [auth0/cosmos#156]
What do you guys think about making all event/change handlers return the new value and event:

onChange = (value, event) => {...}

I noticed that the switch component returns a value, while input/textareas return events. Switch doesn't support a change handler currently.

**Comment by siddharthkp** [comment]
I'm glad you asked that!

I've been thinking about that.

Just passing the value solves 99% of the use cases and makes for a great API. I would like to make `Input`, `Select`, `TextArea`, etc. behave the same. In some custom components, that's the only solution (example: `Switch` and `Tabs`)

To accommodate 1% case where you need to have access to the event, (example `preventDefault`), we have to provide both. This is where it becomes tricky.

As you mentioned, `Input` and `TextArea` transparently pass the `onChange` event through. The API would be something like this:

```jsx
<Input onChange={ (event) => console.log(event.target.value) } />
```

This is what you'd expect from the `onChange` in React. We don't want to break that.

A good way to do this is to pass the value as a second param, it's our little thing to help folks out 😉 

```jsx
<Input onChange={ (event, value) => console.log(value) } />
```

What should be the behaviour in `Switch`?

```jsx
<Switch onChange={ (value) => console.log(value) } />
```

This is inconsistent with the on in `Input`, it sounds horrible if different components have inconsistent signatures.

The solution I'm tending towards looks something like this:

```jsx
<Input onChange={ (event, value) => console.log(value) } />
<Switch onChange={ (event, value) => console.log(value) } />
```

where `event` is a synthetic event with `target.value`, `preventDefault` and other common elements to help out.

This might be stepping into risky territory, but as long as we can through a warning in dev mode when someone uses an undefined property, we should be fine?

**Comment by astanciu** [comment]
you could argue that switch should also send it's event, along with value. Switch is effectively a checkbox and that has an event.

The reason I was thinking of passing (value, event), vs (event, value) was exactly this, keeps things consistent when you don't have an event and thus have value be the first arg.

**Comment by siddharthkp** [comment]
> you could argue that switch should also send it's event, along with value. Switch is effectively a checkbox and that has an event.

That might not be true for all components. Example: Tabs (We can make them use checkboxes if there's enough value in it)

> keeps things consistent when you don't have an event and thus have value be the first arg.

I see where you're coming from, but I'm scared to break the convention that you'd expect when not using cosmos.

**Comment by astanciu** [comment]
>but I'm scared to break the convention
Why? :) I say let's build whatever makes our lives easiest, not what other libraries did in the past. 90% of the time, you just need the value. Putting it second would force all code to look like:

onChange = ( _ , value) => { ... } // ESLint complains about unused variable '_'

This is just my 2c though, if the majority prefer it like this, nbd

**Comment by siddharthkp** [comment]
>  I say let's build whatever makes our lives easiest, not what other libraries did in the past. 90% of the time, you just need the value. 

That makes a lot of sense. I need to think a little more about this, majority of early users will be migrating their existing code, so that's a factor 😢 

> Putting it second would force all code to look like:

I think ESLint doesn't complain when it's before a function param that is used.

**Comment by nkohari** [comment]
@siddharthkp Let's turn this into an action, or close it. Do we want to make any changes to our existing code for this?

**Comment by siddharthkp** [comment]
@nkohari Removed not-actionable, let's implement value as the second parameter.

**Comment by nkohari** [comment]
Closing in favor of #602, which describes the action we need to take.
