### ISSUE TITLE
Make prop table reliable

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#157]
Alt title: Make it work like you would expect it to work

Changes are not handled properly in the prop table.

- [x] String values are confusing, quotes are applied implicitly.
- [x] Enums are not supported
- [x] Default props once set not be changed

**Comment by landitus** [comment]
I would add: 
Change the way an empty input is displayed in the docs table. Now it shows null, but I think it's more friendly to have just an empty input.

<img width="846" alt="screen shot 2018-05-17 at 08 36 42" src="https://user-images.githubusercontent.com/239215/40181349-84245dee-59ae-11e8-9cd9-a7c82e213a8b.png">
