### ISSUE TITLE
Support inline layouts in Form

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#158]
The form can also define how the fields will be arranged. More like a form layout component: horizontal, vertical and inline.

- [x] Horizontal: to horizontally align the labels and controls of the fields. 
- [x] Vertical: to vertically align the labels and controls of the fields
- [ ] Inline: to render form fields in one line.

(Descriptions and names taken from Ant.design)

![forms](https://user-images.githubusercontent.com/239215/34587609-c39abb10-f187-11e7-9e66-a9c3dea03ded.png)

**Comment by landitus** [comment]
I would say we are missing the **inline layout**, which allows labels on the left, aligned left and all form fields in a row.

**Comment by landitus** [comment]
Btw, I still find it more clear to use horizontal, vertical and inline, instead of label-on-top, etc. Mainly because both horizontal and inline have labels on the side/at the left of the field

**Comment by siddharthkp** [comment]
`inline` is a good name, but horizontal and vertical aren't that obvious on the top level Form

`Form layout="horizontal"` sounds like it will lay out a form horizontally (but that's inline)

**Comment by nkohari** [comment]
@landitus Do we still want an `inline` layout for forms?

**Comment by landitus** [comment]
Yes, the use case is out there, though its not very common use. I was in doubt if a Stack component would solve the inline layout, but I think there are lots of things to check for: validations, messages, whether or not to show labels on the fields.
