### ISSUE TITLE
Alert Building Block is broken.

### ISSUE THREAD

**Issue by him2312** [auth0/cosmos#1660]
**Description of the bug**
SyntaxError: Unexpected token (1:57) appears on the documentation in the Building Block -> Alert section.

**Expected behavior**
Change `title={Notice!}` to `title="Notice"` for proper preview of the Alert preview.

**Screenshots**
<img width="855" alt="Bug Screenshot" src="https://user-images.githubusercontent.com/11074657/62464555-8a0de300-b7aa-11e9-91c7-0b90bf3a189c.png">

**Cosmos version:**
Checked on 0.31.0 to 0.26.0, same behavior is there.

**Additional context**
Change `title={Notice!}` to `title="Notice"` for proper preview of the Alert preview.

**Comment by loginist** [comment]
Fixed in https://github.com/auth0/cosmos/pull/1662
