### ISSUE TITLE
Global or common CSS declarations

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#17]
Usually the `font-family`, `line-height` and other utilities like `box-sizing` and `text-smoothing` are declared only once in the `<body>` tag (or with *) for global inheritance. Where should we declare this global styles?

**Comment by siddharthkp** [comment]
Feedback from the meeting: 

1. Make resets optional: Useful for folks migrating their existing applications
2. Component wise resets? Not sure how to do this, but importing a `Button` shouldn't change your Forms

**Comment by nkohari** [comment]
@landitus How do we turn this into an action?

**Comment by siddharthkp** [comment]
I think we can close this

- We automatically apply all resets. They are not optional.
- They all live in one file: `_helpers/globals`
- We only needed to add line-height to `sc-` elements. That's the only difference from the old styleguide
