### ISSUE TITLE
Expose tokens through a theme api

### ISSUE THREAD

**Issue by rodrigo-picanco** [auth0/cosmos#1707]
Hello everyone at auth0. Thank you for the amazing project. 

I'm having trouble trying to figure out how to extend the project's theme, just to tweak some colors and font's to my linking and needs. 

I wonder if we could have something like this in the API: 

`const App = () => <ThemeProvider theme={theme}`

With the theme being and extension of your theme like in: 

```js

import { theme } from '@auth0/cosmos'

export default {
 ...theme,
 colors: {
   primary: '#fff'
 }
}

```

Maybe something like the https://system-ui.com/ specs also

Thank you again!

**Comment by francocorreasosa** [comment]
Hey @rodrigo-picanco 👋  We're working on it, but have to do some prior work like updating styled-components (https://github.com/auth0/cosmos/pull/1697) and fixing the way we inject global styles (https://github.com/auth0/cosmos/pull/1699) to the cosmos-consuming apps first. 

Thank you for reaching out! 😃

**Comment by rodrigo-picanco** [comment]
Hey @francocorreasosa, thank you for your answer. If there's anything I can do to help let me know.

**Comment by ferreiravinicius** [comment]
While we can't extend the cosmos theme I managed to tweak fonts in 2 different ways:

<details>
<summary>
Using createGlobalStyle - need to be placed after their CssBaseline
</summary>

```javascript
import React from 'react';
import { CssBaseline } from '@auth0/cosmos';
import { createGlobalStyle } from '@auth0/cosmos/styled';

const CustomBaseline = createGlobalStyle`
  body {
    font-family: 'Roboto', 'Arial', 'sans-serif';
  }
`
const App = () => {
  return (
    <>
      <CssBaseline />
      <CustomBaseline /> 
      {/* <YourRealAppGoesHere /> */} 
    </>
  );
}

export default App;
```
</details>

<details>
<summary>
Creating wrapper div with styled
</summary>

```javascript
import React from 'react';
import { CssBaseline } from '@auth0/cosmos';
import styled from '@auth0/cosmos/styled';

const Wrapper = styled.div`
  font-family: 'Roboto', 'Arial', 'sans-serif';
`;

const App = () => {
  return (
    <>
      <CssBaseline />
      <Wrapper>
        {/* <YourRealAppGoesHere /> */}
      </Wrapper>
    </>
  );
}

export default App;

```
</details>

Yet not sure if any of those approaches will impact in anything else.
