### ISSUE TITLE
Always scale deployment instances to 1

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#186]
Details here: https://github.com/siddharthkp/now-cd/issues/5

**Comment by nkohari** [comment]
@siddharthkp Is this adequately covered by https://github.com/siddharthkp/now-cd/issues/5, or do we need an issue on the Cosmos side also?

**Comment by siddharthkp** [comment]
We can close this one

**Comment by landitus** [comment]
uipi!
