### ISSUE TITLE
Input: Are readonly and disabled redundant?

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#19]
<img width="680" alt="screen shot 2017-11-03 at 2 46 22 pm" src="https://user-images.githubusercontent.com/1863771/32508621-ebd6fff2-c410-11e7-960f-686c174dd336.png">

These seem very close in use cases.

From slack:

> I think the one with different opacity comes from an use case I found where the input is not available until another event enables it. Like if a checkbox is checked that field will become full opacity and editable. Now that you pointed out, it's very edgy. Also, the label should have the same reduced opacity of the field to make more sense.
> The read-only is widely used and we'll definitely keep it. I can track the "disabled" use case to see if it still makes sense to have it here.
> -- @landitus

**Comment by landitus** [comment]
The `read-only` is set to an input to prevent modification of the input’s value. This element can get focus, while the `disabled` attribute will not. A real-world use case for the disabled field is when another fields value acts a conditional to enable the related field. It's not very common, yet I've seen it happening. 

This answer has some good points regarding which one gets sent to the form: https://stackoverflow.com/a/7730719/272553

**Comment by siddharthkp** [comment]
Do we need both?

**Comment by nkohari** [comment]
@landitus @siddharthkp Should we turn this issue into an action, or close it?

**Comment by siddharthkp** [comment]
We didn't implement `disabled` and nobody died
