### ISSUE TITLE
Get data out of form

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#198]
How does one get data out of form?

- Do you give `onChange` on each element?
- Should we implement a `Form.getData()` which returns an object
- Does it need to push rather than pull, which means the top level `Form` should have an `onChange`

@nkohari Any advice here?

**Comment by nkohari** [comment]
Honestly, I've seen a few different attempts in various libraries to solve this problem, and I think it always ends up being less convenient than doing it manually using a `handleChange` thunk.

Here's an example of what I mean:

```jsx
class MyForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = { item1: "", item2: "", ... };
  }
  handleChange = name => evt => {
    this.setState({ name: evt.target.value });
  }
  handleSubmit = () => {
    // If we want to pass the state to a consuming component,
    // our component can accept an onSubmit function as a prop
    this.props.onSubmit(this.state);
  }
  render() {
    return (
      <Form onSubmit={this.handleSubmit}>
        <Input value={this.state.item1} onChange={this.handleChange("item1")} />
        <Input value={this.state.item2} onChange={this.handleChange("item2")} />
        ...
      </Form>
    );
  }
}
```

The `handleChange()` function takes a field name and returns an event handler that will alter the corresponding value inside the state of `MyForm`.

We should definitely avoid something like `form.getData()` -- I've done it that way myself in the past and it became very confusing to manage. Actually, avoiding calling functions on child components in general is a good idea. React really pushes you to pass functions down to child components and have them call them when they need to pass data back up to their parents.
