### ISSUE TITLE
prop for default selection

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#214]
We have landed on 2 names for the same behaviour in different components:

[Select](https://auth0-cosmos.now.sh/docs/Select) uses `defaultSelected: true`, [Tabs](https://auth0-cosmos.now.sh/docs/Tabs) uses `selected = true`

```jsx
<Select
	options={[
		{ text: 'One', value: 1, defaultSelected: true},
		{ text: 'Two', value: 2, select: true },
	]}
/>

<Tabs>
	<Tabs.Tab label="Tab 1" defaultSelected>first</Tabs.Tab>
	<Tabs.Tab label="Tab 2" selected>second</Tabs.Tab>
</Tabs>
```

If we had to pick one for consistency, which one should it be?

[![](https://api.gh-polls.com/poll/01C5NSSFBY75EJ67JC7VQ8ZAM6/defaultSelected)](https://api.gh-polls.com/poll/01C5NSSFBY75EJ67JC7VQ8ZAM6/defaultSelected/vote)
[![](https://api.gh-polls.com/poll/01C5NSSFBY75EJ67JC7VQ8ZAM6/selected)](https://api.gh-polls.com/poll/01C5NSSFBY75EJ67JC7VQ8ZAM6/selected/vote)

**Comment by landitus** [comment]
Does the same prop get uses for default selected and when the state changes the selection?

**Comment by siddharthkp** [comment]
> Does the same prop get uses for default selected and when the state changes the selection?

Good question! Because, we don't control state, for us it's only prop

**Comment by nkohari** [comment]
We're pretty much only targeting managed components, right? (We don't want to manage any state ourselves.) Do we need `defaultSelected` at all, or is `selected` sufficient?

Related: I notice that we have some inconsistency about child components too. With the new `DialogAction` model, we actually have three distinct APIs:

1. Child components, for example `<Tabs>` and `<Tabs.Tab>`
2. Arrays of shapes, like those used with `<Select>`
3. Arrays of objects, like `DialogAction`

We should probably standardize on one of these, or at least have a good understanding of which to use when (and document our reasoning!)

**Comment by siddharthkp** [comment]
> Do we need defaultSelected at all, or is selected sufficient?

I think `selected` is sufficient (we don't want to have a say on the default/subsequent state)

> we actually have three distinct APIs

Oh my! I completely missed this. That's a really good catch. 

In terms of API, child components give you more control over the rendering than a prop of shape | object. 

1. I'm not super confident if our usage is consistent with the customisability we intend. Example: Tabs are pretty rigid in appearance but follow child components pattern.

2. I'm super okay with picking just one as a blanket approach so that it's predictable for folks to use. 
(This might be super hopeful, after a few weeks of using cosmos, I'd like devs to guess the syntax without referring to the docs and be right about it)

**Comment by siddharthkp** [comment]
Already implemented, can close this now
