### ISSUE TITLE
Create Danger Zone component to wrap destructive actions

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#234]
Could this just be a special case of the `<Well>` component?

**Comment by landitus** [comment]
It could. Now we're using the Well internally, so the Dz could import the <Well> and style it accordingly.

**Comment by nkohari** [comment]
@landitus Do we still want this component?

**Comment by siddharthkp** [comment]
Implemented in https://github.com/auth0/cosmos/pull/847
