### ISSUE TITLE
[TextArea] Font size of code should be smaller than regular text

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#244]
Should be 12/13px?

**Comment by siddharthkp** [comment]
@landitus Manage has the same size for both right now, what's our call here?

**Comment by landitus** [comment]
I think it should be smaller still. I've tried 13px and works. The issue will be that the input height will decrease as well. We'll need to add a fixed height value to inputs. Eventually this height will depend on the input size prop (for smaller or bigger inputs).

**Comment by nkohari** [comment]
Closed by #273.
