### ISSUE TITLE
Rollup: Documentation Tweaks

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#246]
A few minor bugs:

- [ ] ActionInput: Add documentation about form actions (this was added to TextInput already in #224, is that sufficient?)
- [x] TextArea: Change small textarea to have 3 lines
- [x] TextArea: Remove error example
- [x] TextArea: `onChange` prop doesn't appear in the props table
- [x] TextInput: Remove error example
- [x] Tooltip: Add documentation for `content` property

Final cleanup actions:

- [ ] Ensure that all components show how to `import` it from the cosmos package
- [ ] Ensure that all components have a props table and playground
- [ ] Ensure that all components have a description

**Comment by siddharthkp** [comment]
This wasn't on the list, but came in the way: https://github.com/auth0/cosmos/pull/254
