### ISSUE TITLE
[Paragraph] Add documentation

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#248]

**Comment by siddharthkp** [comment]
We have a `Paragraph` component? 🤔

**Comment by landitus** [comment]
Actually we have a `Text` Component. But it's a span and I think It would be more useful if it's a <p> element. The main difference with a p (and styling) is that when you have multiple lines of text, they get separated. Also, being a block element, is easier to compose. 

Question: would it be ok to just use a `p` tag? or we use `Text` or `Paragraph` ?

**Comment by nkohari** [comment]
Is it possible/acceptable to apply the basic typographic rules (font family, font size) globally? If so, we don't need a `<Text>` tag. This could also allow us to eliminate all of the typographical components like `<Paragraph>` and the `<Heading>`s as well.

Keeping headings might be useful in case we want to apply other rules to them; for example, we may want all headings to have an anchor associated with them to enable deep-linking/tables of contents, etc. I'm not sure where we want to draw the line on components that just add styles.

To be honest, `<Link>` could fall into this category as well, but I can see the value in keeping it around if we want to add support for client-side routing.

**Comment by siddharthkp** [comment]
We do already some font stuff globally: https://github.com/auth0/cosmos/blob/master/src/components/atoms/typography/index.js#L5-L14

Can add `p`, `section`, etc. to that.

I'm not sure if we can add margin for `p` or font size for headings globally because of the way folks will transition to cosmos from their apps. We might end up overwriting their styles, our components should be opt-in

**Comment by landitus** [comment]
Makes sense. In that case we should go for the component route for the text, headings, links elements as well, right?

**Comment by nkohari** [comment]
Another option to throw into the mix: we could add a common CSS class like `cosmos` to all of our components, which would allow us to apply the styles globally across all components in Cosmos without leaking the styles. For example:

```
.cosmos {
  font-family: ...;
}
.cosmos p {
  margin-bottom: ...;
}
```

The more I consider it, the more I think we might want to avoid components for typographical elements unless it's necessary. It may just be adding more things that users need to learn without bringing a whole lot of new functionality to the table.
