### ISSUE TITLE
[Empty State] Icon should be light blue instead of gray to match design

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#251]

**Comment by siddharthkp** [comment]
@nkohari I think this bug does not exist anymore 😄

**Comment by nkohari** [comment]
This is what it looks like on master now:

![screen shot 2018-02-12 at 12 17 22 pm](https://user-images.githubusercontent.com/1576/36109887-b451f9ae-0fee-11e8-9b7f-8e223a5e3626.png)

@landitus Should the empty state icon be blue here, or is gray correct?

**Comment by landitus** [comment]
Let's make it look like in production (ignoring the red color):

- [ ] Use the 'plus' icon inside the button
- [ ] Use lightblue for the icon
- [ ] Tweak spacing between elements

**Comment by nkohari** [comment]
Closed by #279.
