### ISSUE TITLE
Give back

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#252]
We depend on multiple open source projects that are built by developers just like us!

Use `npx thanks` in your terminal to see the list 😄 

<img width="1363" alt="screen shot 2018-02-09 at 9 53 57 am" src="https://user-images.githubusercontent.com/1863771/36011710-37224df6-0d7f-11e8-8000-f2299e646495.png">

These are the ones that I'd like to mention:

1. webpack and babel are underlying deps that the whole community relies on, we should support them as a company if we don't already 🙂
2. Two packages that we benefit immensely from in cosmos are `styled-components` and `markdown-to-jsx`, it has saved us a truckload of both time = money. Both of these are maintained by folks part time and probably the ones that could use our help the most.
3. Best for last, we depend on 161 packages built by sindresorhus!! (including nested dependencies). He's dedicated to open source full time and depends on the community to fund him.

We're building cosmos to help us be more effective as a company and save money/make more money. If we can contribute a tiny part of this back to folks that we depend on, it would be ❤️

Just a thought 🙂

**Comment by nkohari** [comment]
This definitely important, and I agree completely. It's an ongoing thing that we need to make sure we do, so we'll never be "finished". As a result I'm going to close the issue for now.
