### ISSUE TITLE
Expressive example in prop table

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#259]
The format for prop type is like this.

```jsx
<Tooltip {props}>Hover over me</Tooltip>
```

&nbsp;

In the case of required props without defaults, the example looks incomplete. Example: `content` in `Tooltip`

```jsx
<Tooltip {props}>Hover over me</Tooltip>
```

results in this hanging black tooltip:

<img width="104" alt="screen shot 2018-02-12 at 10 05 51 am" src="https://user-images.githubusercontent.com/1863771/36083753-562cf642-0fdc-11e8-8db4-72ed418683f8.png">

&nbsp;

The workaround right now is hardcoding the prop (kinda):

```jsx
<Tooltip content="This is a placeholder" {props}>Hover over me</Tooltip>
```

The problem with this approach is you end up with duplicated props when you use the prop table. The latter prop is the one that's picked up, (magic!) but it does look ugly.

<img width="790" alt="screen shot 2018-02-12 at 10 08 40 am" src="https://user-images.githubusercontent.com/1863771/36083785-bbc49e7e-0fdc-11e8-9694-92ff44a41f94.png">

Proposal:

Being able to add default values for the example as a prop (object) which only works in the docs and does not reach the document.

```jsx
<Tooltip  {props} defaults={ { content:"This is a placeholder", top: true } }>Hover over me</Tooltip>
```

This is also magic but if it is predictable for us (documentation writers), we can hide the ugly parts from users (documentation readers)

**Comment by siddharthkp** [comment]
@landitus @beneliflo Thoughts?

**Comment by landitus** [comment]
> Being able to add default values for the example as a prop (object) which only works in the docs and does not reach the document.

- What do you mean by `document`?
- `defaults={ { content:"This is a placeholder", top: true } }>` won't be shown in the code editor part, right?

**Comment by siddharthkp** [comment]
> What do you mean by document?

I think I meant those are the defaults for documentation only, they are not part of `Component.defaultProps`

> defaults={ { content:"This is a placeholder", top: true } }> won't be shown in the code editor part, right?

Nope, we gobble that up

**Comment by landitus** [comment]
mmm, I see. We'll need to find another solution then.

**Comment by landitus** [comment]
So, maybe this could work!! and solves also https://github.com/auth0/cosmos/issues/488
