### ISSUE TITLE
Extra <pre> element wrapping the headings of the doc pages

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#277]
This extra `<pre>` tag causes text overflowing the container and other issues. Not sure why this is generated, but we should remove it.

<img width="1364" alt="screen shot 2018-02-14 at 20 30 11" src="https://user-images.githubusercontent.com/239215/36233735-1cc9cf1a-11c6-11e8-9a3d-9384558805fb.png">

**Comment by siddharthkp** [comment]
It's added by `markdown-to-jsx`, not by us. So we can't get rid of it. But I did overwrite white-space  for header so that it works nicely.

**Comment by landitus** [comment]
Ok! I think we're all with that fix! Shall we leave this open to address it later?
