### ISSUE TITLE
Ability to add links (and basic formatting) in closed components

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#278]
I'm wondering about having the ability to add some basic formatting (like **bold**, `code` and [links](https://auth0.com)) to text that is inputed via props. The example below is the Empty State. Just thinking out loud, any text prop will usually need formatting like links, code or bold. Like a markdown-kind-of-freedom... where a plain string will be too limiting. A similar case is found in the `Form Field` helper text. Maybe we could review them together or think of how to approach it. 

Say we want to add a Read more link after the text, like in the image: how could we achieve this? 

<img width="442" alt="screen shot 2018-02-14 at 20 51 31" src="https://user-images.githubusercontent.com/239215/36234276-ddd52612-11c8-11e8-8ed1-948f624ae642.png">

```
<EmptyState
      icon="clients"
      text="No clients have been created."
      action={{
        icon: 'add',
        text: 'Create Client',
        method: function() {
          /*...*/
        }
      }}
    />
```

**Comment by nkohari** [comment]
We now have an issue (#365) for implementing a possible solution to this, so I'm going to close this issue. If this goes well, and we want to add this functionality to other components like `EmptyState` or to all Actions, we should create new issues for those! 😄
