### ISSUE TITLE
Button icons don't react to hover/focus states

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#285]
Icons inside `Button` (including the one in `Form.Field`) do not get the hover styles.

This is because `Icon` has a `color` prop which overwrites any styles that the parent wants to add to it 😢 

I worked around this for the copy code button in docs, but I had to use `Icon` instead of `Button` and maintain the state, which seems to much work

@nkohari ideas?

**Comment by nkohari** [comment]
Checked into this again. Unless I'm missing something, it seems like we don't have any hover styles being applied to the contents of `Button`. @siddharthkp Do we still need this issue?

**Comment by siddharthkp** [comment]
duplicate of https://github.com/auth0/cosmos/issues/1075
