### ISSUE TITLE
Review Heading component

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#286]
We need to review the headings to have a simple scale like:

<img width="402" alt="screen shot 2018-02-15 at 11 27 23" src="https://user-images.githubusercontent.com/239215/36285734-931b8238-128b-11e8-8e1d-a64d894b28d9.png">

Subheader could be the Heading 4.

The concern will be around adding intermediate headings in the future will break this structure and cause a lot of headaches. I agree, so we need to have a look at this in depth and commit to the heading structure that fits our needs.

**Comment by siddharthkp** [comment]
Add some more context here before we forget about it 😅

**Comment by nkohari** [comment]
- [ ] Remove H5, replace H4 with current H5 style
- [ ] Add line height property

**Comment by nkohari** [comment]
Closed by #301 and #303.
