### ISSUE TITLE
Long term roadmap

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#287]
Feel free to dump your thoughts here and then we consolidate them nicely later
(I'm just making sure I don't forget anything 😅)

&nbsp;

Let's put them in milestones/projects with the month name it might land.

&nbsp;

In no particular order:

1. Polishing the UI
- Don't have much to say here, we need to review all the things and make them pixel perfect.

&nbsp;

2. Improvements to the documentation: 
- Make required props visible in docs https://github.com/auth0/cosmos/issues/97
- Make propTypes warning visible in docs https://github.com/auth0/cosmos/issues/86
- Expressive example in prop table  https://github.com/auth0/cosmos/issues/259
- Evaluate variables in prop types https://github.com/auth0/cosmos/issues/253
- Add validation rules for documentation https://github.com/auth0/cosmos/issues/283
- Autocomplete plugin for editors https://github.com/auth0/cosmos/issues/105

Documentation website
- Polish text

&nbsp;

3. Tests
- Figure out a testing strategy https://github.com/auth0/cosmos/issues/5
- Snapshot tests for all the presentation component
- Automate visual diff for pull requests https://github.com/auth0/cosmos/issues/15 (test all edge cases)

&nbsp;

4. Design land
- Sketch library (One of the problems we are solving is the communication between designers and developers. The workflow isn't complete until we go from design to deployment)
- Take an inventory of all the components and pick standards
- Start adding missing components + start changing built components according to the new standards
- Work on the redesign, don't know if this is in the 9 month plan but we can start this in a parallel 2.x branch.

5. Components
- Tokens: Review, polish and document a strong design tokens system
- Review components to use Tokens

**Comment by landitus** [comment]
I've added the Tokens review we are going to have to work on soon. A good starting point is: https://github.com/auth0/cosmos/pull/176

**Comment by nkohari** [comment]
Closing this since it's non-actionable. We can still refer back to it if necessary.

**Comment by landitus** [comment]
We've moved this list to the Roadmap internal docs, which for now is better, IMO
