### ISSUE TITLE
Change the components documentation url address to lowercase (and url-friendly)

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#293]
We have URLs for components like `http://.../docs/ButtonGroup`. We should change them to be more url-friendly:

- Lowercase
- Use dashes to separate words

Like `http://.../docs/button-group`

I don't have a technical reason other than they look prettier and more standard. Also, if you type the lowecase version you'll get an error page.

wdyt?

This relates a bit with https://github.com/auth0/cosmos/issues/294

**Comment by siddharthkp** [comment]
Ideal solution for me:

Pick the one that looks pretty 
Redirect the other one so that both work

**Comment by landitus** [comment]
Makes sense, I would go for `http://.../docs/button-group` then
