### ISSUE TITLE
Should the components' name be "human friendly" in sidebar and page titles?

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#294]
I can't seem to find a better title for this idea, sorry 😅And maybe it's not a big deal, just take this as a propsal.

<img width="981" alt="screen shot 2018-02-16 at 00 19 53" src="https://user-images.githubusercontent.com/239215/36292303-7d1a06a2-12af-11e8-93b3-8f5364418aee.png">

There could be an argument that the actual component's name is CamelCase. I get it. It also relates to wether the docs are purely technical or have design and UX guidelines embedded in them. If we want to unify the language between devs and designers, maybe it makes sense to use a more natural naming convention, at least for the sidebar and the component's page title. Like when we name the symbols in Sketch, it would make sense to have **Form Group**, instead of **FormGroup**.  Also, it looks prettier 😁

This will affect how we refer to the component in the documentation too, I guess.

wdyt?

This relates a little bit to https://github.com/auth0/cosmos/issues/293

**Comment by nkohari** [comment]
IMO, it should match the code for clarity.

**Comment by landitus** [comment]
My take was to have a single, human friendly name to call components so that both designers and devs fell comfortable. Like when talking about a component in Slack, it would make sense to refer to the `Form Group` instead of the `FormGroup`.

**Comment by nkohari** [comment]
That makes sense, and I don't know if there's a "right" solution. The code examples in the docs will make the actual component name pretty obvious anyway. I'd be okay with either.
