### ISSUE TITLE
Small design tweaks for buttons

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#299]
Just some small tweaks to the icons and some colors:

<img width="512" alt="screen_shot_2018-02-14_at_19 09 57_1024" src="https://user-images.githubusercontent.com/239215/36313168-8487601e-130f-11e8-97ce-822d374480eb.png">

**Comment by siddharthkp** [comment]
Image missing?

**Comment by landitus** [comment]
Done in https://github.com/auth0/cosmos/pull/311
