### ISSUE TITLE
Tidy up Connections table

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#322]
Just leaving this here to not forget :) I saw a note on connections.js and wanted to chime in:

- [ ] For the nested `Stack`, we could maybe have a data array like we have in the **Clients table** and then iterate it inside the `List`.

- [ ] Also, I think we need to figure out an alternative this: 
```
<Connection.Type>
      <Icon size={16} name={props.icon} />
      <span>{props.name}</span>
    </Connection.Type>
```
It only does an inline-block alignment of the icon and the word, which is super low level.
```
Connection.Type = styled.div`
  span {
    display: inline-block;
    vertical-align: middle;
  }
`
```

This is were a `Stack` could also be used (but now it would not do inline with margins). This is the typical case of the [Flag element](https://csswizardry.com/2013/05/the-flag-object/). I feel Stack is starting to look confusing, but maybe we need to review it and see how it would work for Lists or other alignment between components.

**Comment by nkohari** [comment]
Closed by #442.
