### ISSUE TITLE
Expose parts of cosmos to use in other projects

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#323]
If we have a recommended approach for building local components (in projects that use cosmos), that can help us make a few things simpler for teams and ourselves.

1. Tokens, this is the most basic building block. If we don't have a component, we want folks to use our tokens.
2. Documentation, if we pull out our documentation as a tool, it can help bring local components to cosmos faster (https://github.com/auth0/cosmos/issues/360)
3. Testing strategy for both new components and local components that compose things from cosmos

**Comment by landitus** [comment]
Tokens FTW!

**Comment by siddharthkp** [comment]
Moved to discussions: https://github.com/orgs/auth0/teams/design-systems/discussions/10
