### ISSUE TITLE
Add documentation about build steps

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#324]
1. Build from source (this is our default right now)
2. Using built files (idk if we should have this)
3. Using with `create-react-app`
4. Using with custom webpack config: ignores, tree shaking, etc.
5. Using tokens in a `sass`/`less` project

**Comment by landitus** [comment]
We could re-inforce that the intended usage of Cosmos is through the import, all pre-packaged, right? The build from source is only for the contributing guidelines.

**Comment by siddharthkp** [comment]
> pre-packaged

This might not be true. Because there is already a bundler (webpack) on the way, it adds little value for us to ship compiled/transpiled code.

**Comment by siddharthkp** [comment]
We don't even need this anymore ✨
