### ISSUE TITLE
Fix tokens for CI

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#329]
We have activated SSO in Github and as a result, the tests before each commit are failing. 
I'm seeing this in Travis: 

```
  error: 
   { message: 'Resource protected by organization SAML enforcement. You must grant your personal token access to this organization.',
```
Can you take a look @siddharthkp ?

**Comment by siddharthkp** [comment]
Oops!

It just required re-authorization, we're good now!

**Comment by siddharthkp** [comment]
I take that back, it didn't work :(

**Comment by landitus** [comment]
😱

**Comment by siddharthkp** [comment]
And we're back after the github API relaxed
