### ISSUE TITLE
3 bugs for TextInput

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#331]
Playing around with the Props table of the Text Input I feel it would be more powerful if:

- [ ] Whatever value you input in the field would stick around and have the mask applied properly.

![kapture 2018-02-27 at 12 07 24](https://user-images.githubusercontent.com/239215/36736298-03720fdc-1bb7-11e8-801b-eb55b608df1f.gif)

- [ ] Avoid the collision of styles between `code` and `mask`

![kapture 2018-02-27 at 12 08 01](https://user-images.githubusercontent.com/239215/36736304-06b9bef6-1bb7-11e8-8e67-279952b3506d.gif)

- [ ] Inputs in the props table should change the rendered component

<img width="824" alt="screen shot 2018-02-27 at 16 50 18" src="https://user-images.githubusercontent.com/239215/36751254-6c6aab62-1bde-11e8-93c6-2b9a092fe745.png">

**Comment by nkohari** [comment]
The first one is due to the use of `defaultValue` instead of `value`. Only the initial (default) value will be masked.

**Comment by siddharthkp** [comment]
2nd one can be solved by adding [internal validation props] (https://github.com/auth0/cosmos/blob/master/src/components/atoms/button/index.js#L229-L231)
