### ISSUE TITLE
Update install guide in docs

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#333]
Pulling Cosmos from `npm` as described in the **install guide** is not going to work, yet. I think it's best if we update this doc with the correct info until we figure that out. That way, all we publish reflects the actual state of the project and we avoid confusion. wdyt?

**Comment by siddharthkp** [comment]
> Pulling Cosmos from npm as described in the install guide is not going to work

Why not? 🤔

**Comment by landitus** [comment]
Sorry if I’ve phrased it wrong! I meant if its not working at the moment, or doesn’t reflect the current status of the library. ☺️

**Comment by landitus** [comment]
Let’s document the temporary solution then! ☝️
