### ISSUE TITLE
Figure out how to override the margin top on first paragraph (or remove margins all together)

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#381]
In `connections.js` we override the first <Paragraph> Component to remove the top margin and avoid unwanted space.

```
const FirstParagraph = styled(Paragraph)`
  margin-top: 0;
`
```

**Comment by landitus** [comment]
Directly related to: https://github.com/auth0/cosmos/issues/389

**Comment by siddharthkp** [comment]
Tackled in https://github.com/auth0/cosmos/issues/1084
