### ISSUE TITLE
Additional text styles (or components)

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#384]
We have a few more text styles (in addition to the Paragraph) that could be extracted as components that we can use inside other components:

- **Smaller paragraph**: Could be called **Caption** (as it is lighter and smaller)

<img width="672" alt="screen shot 2018-03-08 at 23 54 17" src="https://user-images.githubusercontent.com/239215/37188100-3ea52d10-232c-11e8-99ed-6d7ce6daa925.png">

<img width="154" alt="screen shot 2018-03-08 at 23 53 22" src="https://user-images.githubusercontent.com/239215/37188118-51c45e3e-232c-11e8-99d7-f85b45951686.png">

<img width="233" alt="screen shot 2018-03-08 at 23 53 33" src="https://user-images.githubusercontent.com/239215/37188111-4ab10912-232c-11e8-8058-63a28a4f7d18.png">

- **All Caps Text:** These are a very special style in Auth0 but it's used for some small titles and to denote the Type of entities in some parts of the application

<img width="501" alt="screen shot 2018-03-08 at 23 53 39" src="https://user-images.githubusercontent.com/239215/37188109-47459eb4-232c-11e8-8cdd-04f67abb7120.png">

<img width="326" alt="screen shot 2018-03-08 at 23 54 13" src="https://user-images.githubusercontent.com/239215/37188102-40f5e654-232c-11e8-9cad-ca6e14be11a1.png">

<img width="282" alt="screen shot 2018-03-08 at 23 53 18" src="https://user-images.githubusercontent.com/239215/37188126-5a32cd1c-232c-11e8-899e-5cceb12461ef.png">

With these new typography styles (plus Paragraph and Heading) we should be covered.

**Comment by nkohari** [comment]
I guess I'm not sure what the difference between `Caption` and `Paragraph` is, from a visual standpoint. Also, I'd say `Caption` sounds like it's related to an image or diagram in some way.

For the small-caps styling on the text, maybe we need some sort of `<Text>` component after all which would allow a type, ex:

```jsx
<Text type="small-caps">
  ...
</Text>
```

I'm not sure each style merits having a separate component -- and if so, I have no idea what to call them! :)

Now that I'm thinking about it, a good litmus test for components might be whether we can come up with a name for them that effectively conveys their intended use.

**Comment by landitus** [comment]
I think could be done with a Text component as you propose. Polaris also does [something similar](https://polaris.shopify.com/components/titles-and-text/text-style). It's mostly about styling so we could name type="subdued" or type="allcaps" to achieve them. It's a nice option to weight in. 

My only concern would be wether to render them as `p` or `span` and wether the situation would require one or the other. I think most of the time they will be block elements, but maybe I'm wrong and we would need more flexibility. I would do it as block until we run into a different need.

**Comment by nkohari** [comment]
Closed in favor of #421.
