### ISSUE TITLE
Spell-checking text in code inputs

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#386]
We have some inputs with information such as tokens or urls which should no be spellchecked. We could add a prop like spellcheck=false to remove html spellchecking in the inputs.

<img width="506" alt="screen shot 2018-03-08 at 19 59 38" src="https://user-images.githubusercontent.com/239215/37181339-4a4f2236-230b-11e8-9027-eedf6dc655ef.png">

**Comment by siddharthkp** [comment]
We shouldn't have to add a custom prop for this, HTML attributes should always transparently pass through the HTML element.

**Comment by landitus** [comment]
Ok. I think we should document it then, because it’s something useful that we'll improve the user experience in some situations. I think the same about: `autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck=“false"`

If we think about the code prop in the input field, we’ll need to take care of the `autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck=“false”` inside the component, though

**Comment by nkohari** [comment]
@landitus Is there an action to take here?

**Comment by siddharthkp** [comment]
We fixed this at some point

Now, we proxy all the props down to the input, so you can any valid html attributes

[Playground example](https://auth0-cosmos.now.sh/docs/#/playground?code=%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20(%250A%20%20%20%20%3CForm%3E%250A%20%20%20%20%20%20%3CForm.TextInput%20spellcheck=%22false%22%20/%3E%250A%20%20%20%20%3C/Form%3E%250A%20%20)%250A%7D%250A%250Arender(Example)%250A)
