### ISSUE TITLE
Add default and required props information in docs prop table

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#387]
We could add the **default prop** information in the documentation props table and mark the **required props** with an asterisk * 

Example from Ant.design:
<img width="860" alt="screen shot 2018-03-08 at 20 03 18" src="https://user-images.githubusercontent.com/239215/37181453-d5b03e0a-230b-11e8-8c93-e43e6b3df31f.png">

wdyt?

**Comment by siddharthkp** [comment]
Fixed in https://github.com/auth0/cosmos/pull/533
