### ISSUE TITLE
Fix last margin in Button Group component

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#388]
The Button group has a right margin on the last item which adds space and doesn't allow for proper centering. The example below is the dialog.

<img width="351" alt="screen shot 2018-03-08 at 20 42 31" src="https://user-images.githubusercontent.com/239215/37182751-7adffbf4-2311-11e8-9b0b-6f4d3eca843c.png">

**Comment by nkohari** [comment]
Closed by #399.
