### ISSUE TITLE
Margins for Headings and Paragraphs

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#389]
Headings and Paragraphs are one of the core components of a system. In most CSS frameworks (like Bootstrap), all typographic elements have margins (top and bottom) to allow for vertical rhythm while composing long form text. You can have titles, subtitles and paragraphs placed on the DOM and the correct separation would be achieved effortlessly. 

**Example of typographic elements:**
- Tutorials or Quickstarts
- An intro text after a Tab
- Sections and paragraphs between other components (Forms, tables)

Our initial approach had margin-less Headings and Paragraphs. But taking cues from these CSS frameworks techniques, we changed Headings and Paragraphs to have both top and bottom margin. 

The first issue comes from the first paragraph or Heading in a page, which doesn't need the top margin. So, we have overrides for margins at the page level. This is prone to error and maybe calls for a better solution. 

Note that we **do overrides** for these margins at the component level when needed, which is expected, so that seems ok.

I've been thinking about some strategies to avoid overriding the margins:

### Remove all margins, create a Section component 

Remove all margins of the typographic components and create a new parent component, called **Section** or **Text**, which will add proper margins to all Headings and paragraphs inside. This would allow to remove margin top to the first element (which-ever it is) and to the last. So that there's not an extra space below. 

```
<Section>
  <Heading size={1}>This is a title</Heading>
  <Paragraph>This is text</Paragraph>
</Section>
```

([Polaris does something similar](https://polaris.shopify.com/components/titles-and-text/text-container#navigation))

**Alternative: Keep only the margin-bottom, create a Section component**
Almost the same as A): Keep only the margin-bottom and add the margin top when used inside the Text component. The only change is that this is a little more consistent with our (current) spacing approach where all components only have margin-bottom to achieve spacing. 

--- 

I've researched other DS and have not found examples or docs of typography components. Just regular` <p>` and `<h1>` with plain CSS (with top and bottom margins).

Wdyt? Are there another options I'm missing out? Maybe there's a simpler solution! 🤔

**Comment by landitus** [comment]
This idea should take care, among other things, of: 

```
// TODO: Need to figure out how to make the first Paragraph have no margin top. We could add a prop?
const FirstParagraph = styled(Paragraph)`
  margin-top: 0;
`

class Connections extends React.Component {
  render() {
    return (
      <div>
        <FirstParagraph>
          Connections are sources of users. They are categorized into Database,
          Social and Enterprise and can be shared among different applications.
        </FirstParagraph>
...
```

**Comment by landitus** [comment]
Looking at this... I wonder what's the difference between using a `<p>` instead of `<Paragraph>`?

**Comment by siddharthkp** [comment]
> Remove all margins of the typographic components and create a new parent component, called Section or Text

Section ~~Text~~ 👍

How do you define a Section in english? aka How do you explain the usage of Section? 

`FirstParagraph` seems too fragile as an API because it's dependant on exactly how it's used. If there's a header/image before it, then it doesn't give the result we need.

For a developer composing the DOM, these look redundant. It's a sign that our implementation detail is leaking out.

```jsx
<div>
  <TextContainer>
    <Paragraph>
	  Connections are sources of users. They are categorized into Database,
      Social and Enterprise and can be shared among different applications
    </Paragraph>
  </TextContainer>
</div>
```

I'd expect this to work:

```jsx
<Paragraph>
  Connections are sources of users. They are categorized into Database,
  Social and Enterprise and can be shared among different applications
</Paragraph>
```

> Keep only the margin-bottom, create a Section component

I like the sound of this. If every layout/typography component has a bottom-margin, the interface would flow on it's own.

@landitus Where would this break?

**Comment by nkohari** [comment]
@landitus What can we do to move this forward? Or should we move it to discussions?

**Comment by siddharthkp** [comment]
We've made some progress: This issue would be tackled in Layouts https://github.com/auth0/cosmos/issues/1108 + Margins https://github.com/auth0/cosmos/pull/1059
