### ISSUE TITLE
Ease of integration (build config)

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#412]
I touched upon this in: https://github.com/auth0/cosmos/issues/3 and https://github.com/auth0/cosmos/issues/349

So here's the thing, almost all React applications will depend on [`babel-preset-react`](https://babeljs.io/docs/plugins/preset-react/), either by adding because of `create-react-app` or by adding it in their babel config (manage does this)

We use 2 features that are in an awkward spot. 
- [`transform-object-rest-spread`](https://babeljs.io/docs/plugins/transform-object-rest-spread)
- [`transform-class-properties`](https://babeljs.io/docs/plugins/transform-class-properties/)

You can use them in your application (like manage), but a dependency of yours cannot use it (like cosmos). There's a [feature request open in `create-react-app`](https://github.com/facebook/create-react-app/issues/3777).

For now, we have 2 options:

- Ask products to add another line into their babel config:

  ```diff
  {
    "presets": [
      "react",
  +  "auth0-cosmos/babel",
      ["env", { "targets": { "browsers": ["last 2 versions"] } }]
    ]
  }
  ```

- Not use these features

---

#### What difference does it make?

- Even though it's one tiny line, I would like cosmos to be a drop in dependency with no _extra_ configuration needed.

- Folks using `create-react-app` will either have to eject or use something like [react-app-rewired](https://github.com/timarney/react-app-rewired) in order to use cosmos

- There's added benefit we can get from a babel-plugin like enabling better debugging for styled-components: https://github.com/auth0/cosmos/issues/166, so it's not a bad idea to introduce it from the start (or maybe this should be an opt-in feature?)

**Comment by nkohari** [comment]
Maybe a silly question: is there a reason we don't just ship the transpiled JavaScript? It'd be nice to be able to use language features freely inside of Cosmos without worrying about what version of ES (or Babel) consumers are using.

**Comment by siddharthkp** [comment]
> is there a reason we don't just ship the transpiled JavaScript?

My reason is not knowing the right transpile target: ES6 + React presets? ES6? ES5? 

Covered it in #3 :

```
4. What code do we ship? (packaging)
By shipping the source we give the application developers more power in terms of transpilation and tree-shaking.

Example: If the application only supports only the last 2 versions of browsers (manage does that), they have the opportunity to have smaller bundles by shipping ES6 code. If we ship an ES5 bundle, they are taking a performance hit.

On a similar note, if the application uses styled-components already, we don't want to package it with cosmos as well and end up with 2 versions of it.
```
