### ISSUE TITLE
Add support for large-sized Buttons

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#417]
Currently in Manage, there is a large button in addition to the regular-sized ones that we already support. In order for Cosmos to be used in Manage, we need to add a `large` Boolean prop to `Button`.

@landitus could you provide mockups/screenshots of the "large" `Button`?

**Comment by landitus** [comment]
These are the sizes we are going to support for Buttons:

<img width="821" alt="screen shot 2018-03-19 at 16 47 20" src="https://user-images.githubusercontent.com/239215/37618526-4b3e11ce-2b95-11e8-9098-d78b4cc62359.png">

**Comment by nkohari** [comment]
The original description says to add a `large` Boolean prop, but based on this, I'll instead add a `size` prop, which is an enum that supports `default`, `large`, `compressed`, and `small`.
