### ISSUE TITLE
Get approval for new design of primary Button from design team

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#418]
In creating Cosmos, we tweaked the style of the primary button. We should confirm with the design team that the new style is acceptable before it is used by consumers of Cosmos.

**Comment by landitus** [comment]
<img width="418" alt="screen shot 2018-03-22 at 11 29 15" src="https://user-images.githubusercontent.com/239215/37776558-4eaa5490-2dc4-11e8-8988-ba31711fc8ae.png">

Got it! It's the same as the current styleguide
