### ISSUE TITLE
Responsive web design

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#42]
Auth0 products are not responsive today, but's it's a good idea to bake in basic responsiveness to components so that they can adapt to any context and new responsive iterations are possible from the get go.

We should list what a basic responsive needs to comply with.

**Comment by nkohari** [comment]
@landitus Is there a way to turn this into an action, eg. should we review what we've already built and add responsiveness? Otherwise this is an on-going goal, and I'm not sure we need to keep the issue open.

**Comment by siddharthkp** [comment]
One liner for 1.0.0
