### ISSUE TITLE
Change the component's name to be "human friendly"

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#486]
Previous discussion: https://github.com/auth0/cosmos/issues/294

### TL;DR
> My take was to have a single, human-friendly name to call components so that both designers and devs feel comfortable. Like when talking about a component in Slack, it would make sense to refer to the Form Group instead of the FormGroup. Also, naming components in Sketch files and referring to them in UX/docs when using a human-friendly name.

> Most of this thinking comes from the legacy of the Bootstrap library, and the way they've named their components, which seems more natural to me.

As we starting using the docs as our single source of truth and we are having discussions with teams in Slack and GitHub, we should have a canonical name and URL to avoid confusion. 

In a nutshell, we need to rename components in titles and navigation to human readable. For example: `FormActions` becomes `Form Actions`. This will not affect the component name in React. Just in our documentation. It's how we want to refer to them in Slack, Sketch with designers/devs. This is related to the new URL scheme proposal: https://github.com/auth0/cosmos/issues/293

**Comment by nkohari** [comment]
Closed by #493.
