### ISSUE TITLE
Add position prop to Tootip component

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#490]
I've seen use cases of the tooltip being used from the top and bottom. We also had requests for adding position bottom from other crews. Right now we only support `position: top`. It wouldn't hurt in this case to add left and right just to have more flexibility. This would make this small component more powerful.

<img width="785" alt="screen shot 2018-06-06 at 00 56 08" src="https://user-images.githubusercontent.com/239215/41016232-705e68d8-6924-11e8-817c-fbf6102b5662.png">

**Comment by nkohari** [comment]
Closed by #576.
