### ISSUE TITLE
Files keep getting modified and added to git staging

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#495]
Since the latest big yarn update, I've been getting `icons.js` and `changelog.js` modified and added to my git staging area. Do they belong to the .gitignore? I guess the changelog doesn't. How can we fix it?

**Comment by siddharthkp** [comment]
- Merge master
- Delete those files from your machine

Do they still re-appear?

**Comment by landitus** [comment]
Icons are gone. Good. I only get the changelog modified every time.
<img width="1232" alt="screen shot 2018-04-11 at 10 46 30" src="https://user-images.githubusercontent.com/239215/38620746-ba1db080-3d75-11e8-9773-d88b83940e2f.png">

**Comment by nkohari** [comment]
I think the changelog update is just due to the linter reformatting it. The `changelog.json` file doesn't really need to be committed to the repo, I guess, as long as it's built on startup.

**Comment by siddharthkp** [comment]
I thought I added it to ignore in https://github.com/auth0/cosmos/pull/481 

Doesn't look like it 😢

**Comment by landitus** [comment]
Looks solved to me now!
