### ISSUE TITLE
Proposal: Advanced Select component

### ISSUE THREAD

**Issue by astanciu** [auth0/cosmos#507]
I'd like to propose adopting this component: https://github.com/JedWatson/react-select
and just styling it to match the styleguide. 

- Current dropdown looks great, until you drop it down and the native list shows up, which looks out of place and not so great. The selection list should match in style:
![image](https://user-images.githubusercontent.com/1675025/38819817-6efbe4ac-416a-11e8-9f83-d671a64ec116.png)

versus something like:
![image](https://user-images.githubusercontent.com/1675025/38819801-614c7e16-416a-11e8-8ae1-be1d6fd2bd56.png)

- react-select offers a TON of advanced functionality, such as multi-select, async lookups, type-ahead, etc, etc.. would be a ton of work to replicate all this. At over 11K stars, react-select is a very mature component

**Comment by landitus** [comment]
Great! This is definitely a useful one to have in Cosmos! And react-select seems the way to go (with our custom styling).
