### ISSUE TITLE
Table Pagination Component

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#51]
<img width="883" alt="screen shot 2017-12-13 at 13 50 44" src="https://user-images.githubusercontent.com/239215/33995996-79e6ab48-e0be-11e7-9192-9c2963e38a06.png">

@cristiandouce was telling me that we should factor in the pagination component in the Clients table. He also advised it could be used a wrapper to the elements so that they gain pagination.

**Comment by nkohari** [comment]
![screen shot 2018-01-04 at 12 46 43 pm](https://user-images.githubusercontent.com/1576/34576984-c556c88e-f14d-11e7-8336-06ac7b3d53b7.png)

**Comment by landitus** [comment]
I think we should leave this open, as a component request!

**Comment by nkohari** [comment]
Whoops, sorry! I was closing issues in bulk and got this one by accident. Thanks for the catch!

**Comment by nkohari** [comment]
Closed in favor of #526.
