### ISSUE TITLE
Tabs: needs onSelect()

### ISSUE THREAD

**Issue by astanciu** [auth0/cosmos#579]
Chosen tab is lost in a complex component when the state changes and a render happens. Need to be able to keep track of which tab is selected and re-select it after a state change. 

For ex:

```JSX
const setTab = (index) => this.selectedTab = index;

<Tabs onSelect={setTab} selected={this.selectedTab}>
  <Tabs.Tab />
  <Tabs.Tab />
</Tabs>
```

Currently, you can set selected on `Tabs.Tab` but there's no way to programmatically set that based on some condition.

```JSX
<Tabs.Tab selected={what do I have available here to compare?} />
```

**Comment by siddharthkp** [comment]
Good catch! 

This is fairly easy to reproduce. The selected state get's lost on re-render: https://codesandbox.io/s/kxj62y9l9v

The solution you are proposing would always work but it feels like asking for extra work from developers. What if we maintained this inside the component.

It would behaves the way you expect it to (persist selected tab) unless you want to take control by passing the `selected` prop, then cosmos will let you do your thing.

**Comment by astanciu** [comment]
If you can maintain it in the component that would be great... 

Just for thought, there may be use-cases where the developer needs control. For ex, maybe I want to bind React Router paths to certain tabs, so I can have urls that go directly to a tab, like:
`.../users/astanciu/groups`
Which would go right to a Groups tab on the User page

**Comment by siddharthkp** [comment]
Sounds perfect, that's the general strategy we need to take I think @landitus 

Coincidentally, I was adding a react router example just today for the side navigation: https://github.com/auth0/cosmos/pull/583/files?utf8=%E2%9C%93&diff=unified&w=1#diff-90d1f67631698e514efab97b6a7b6beaR7
