### ISSUE TITLE
Add large spinner (with logo) to Spinner component

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#594]
The large spinner is primarily used for loading states between pages. The existing small spinner is used for loading states inside buttons.

I believe the large spinner should be the default one, so that would make a breaking change.

### Actual implementation
https://auth0-cosmos.now.sh/docs/spinner

### Design reference
<img width="659" alt="screen shot 2018-06-08 at 16 24 55" src="https://user-images.githubusercontent.com/239215/41176911-89e80d2a-6b38-11e8-8a62-66ae28e61213.png">

### The API for the spinner could be:

**size: enum**
`default`: spinner with logo 
`small` : spinner without logo

For the light and dark version at first I thought of an `appearance` prop, that defaults to `light`? wdyt?

The docs could use some love and we will now have a Props table in there!

**Comment by francocorreasosa** [comment]
For reference: https://styleguide.auth0.com/#/components/spinner

**Comment by landitus** [comment]
Yes, and obviously there are 4 sizes... but I couldn't find usage of these 4... just 2. So I believe we should start with 2 sizes and later add them if necessary. It will further break the API, if this happens, but wouldn't want to add stuff we are not going to use.

**Comment by nkohari** [comment]
This is marked as a breaking change, but it seems like it will just be additive. Will something be removed or changed in the API?

**Comment by landitus** [comment]
The spinner doesn't have props for size, but the new default size for spinner will be bigger. So it will break the UI unless you specify the prop you want.

**Comment by landitus** [comment]
Added image reference and updated Sketch file.

**Comment by astanciu** [comment]
Something to consider:
an property to define the layout. Default to centered, but can be overwritten to inline
