### ISSUE TITLE
Compound component syntax

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#60]
There are 2 options for compound components, it's a experience choice rather than a technical one*

<img width="885" alt="screen shot 2017-12-14 at 6 39 06 pm" src="https://user-images.githubusercontent.com/1863771/34015811-6e567aac-e0fe-11e7-9aa1-c72dd464ca67.png">

The first approach is more explicit, a parent component brings it's children with it.

```jsx
import Tabs from 'cosmos/tabs'

const ClientScreen = (
  <Tabs>
    <Tabs.Link>Settings</Tabs.Link>
    <Tabs.Content>magic happens here</Tabs.Content>
  </Tabs>
)
```

or 

```jsx
import Tabs, { Link, Content } from 'cosmos/tabs'

const ClientScreen = (
  <Tabs>
    <Link>Settings</Link>
    <Content>magic happens here</Content>
  </Tabs>
)
```

The second one looks better (in my opinion) and works well when used in small files (good coding practice?) when there are no conflicts.

Even in situations where conflicts can happen, the user/developer has an easy workaround:

```jsx
import { Link } from 'cosmos/navigation'
import Tabs, { Link as TabsLink, Content } from 'cosmos/tabs'
//                 ↑↑↑↑     this avoids any naming conflict

const SomethingElseWithALink = (
  <Link>Contact support</Link>
)

const ClientScreen = (
  <Tabs>
    <TabsLink>Settings</TabsLink>
    <Content>magic happens here</Content>
  </Tabs>
)
```

This approach requires the developer to think about conflicts but gives an option to opt-in into the longer/more explicit syntax only when needed.

--

* the technical implication here is that `Tabs.Link` syntax is difficult to [tree shake](https://webpack.js.org/guides/tree-shaking), but it doesn't sound like a probably use case with compound components, they all get used together

**Comment by nkohari** [comment]
For now, we've taken the latter approach (e.g. `Tabs.Tab`) for now; let's revisit this if it causes trouble in the future.
