### ISSUE TITLE
Replace secondaryActions in Form with a (singular) secondaryAction

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#600]
(See #390 for discussion.)

~~Right now, `Form` accepts an array of secondary actions via the `secondaryActions` prop. To standardize and simplify things, we should remove that and replace it with a `secondaryAction` prop, which accepts just a single action.~~

After discussing this on Slack, we want to keep `secondaryActions` as a plural, but only permit a single `destructiveAction`.

**Comment by francocorreasosa** [comment]
Should we do the same with `destructiveActions`?
