### ISSUE TITLE
[API Consistency] Update and standardize call signature of change callback functions

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#602]
(See discussion in #156.)

We want to standardize the signature of all callback functions that are triggered when values change within our components. This will make it more convenient to use Cosmos components in a controlled/stateless fashion.

The standard signature should be:

```ts
onChange(event: Event, value: any): void
```

The first argument should be the `Event` that is passed to the original event handler by React, and the second argument should be the new value held within the component.

**Comment by siddharthkp** [comment]
This might not be a breaking change at all, instead of

`onChange(event: Event)`, you get `onChange(event: Event, value: any)` which shouldn't break any (non-typed) code

**Comment by nkohari** [comment]
Ah, good point!
