### ISSUE TITLE
Props table breaks on Avatar docs page

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#611]
The default props on the `Avatar` docs page don't appear correctly in the table, and when you input props manually, it overrides the defaults with blank props.

Here's a gif of the issue:

![](https://user-images.githubusercontent.com/239215/41302226-559fd506-6e40-11e8-87bb-eb6d645b7e97.gif)

I'm not sure if this issue occurs elsewhere in the docs. @landitus discovered it when reviewing the new `Avatar` PR, and we realized it's already an issue on master.

**Comment by francocorreasosa** [comment]
@nkohari In what branch is this happening, I don't see as many props in the Avatar as in the attached GIF by trying on `master`.

**Comment by landitus** [comment]
in the `avatar-block` branch

**Comment by francocorreasosa** [comment]
👌

**Comment by landitus** [comment]
This was fixed!
