### ISSUE TITLE
Chromatic doesn't catch errors which occur only in the bundled output

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#626]
At some point a bug (#625) was introduced involving the vertical height of components. It only seems to occur in the bundled output, and not in the dev build. Unfortunately this means that Chromatic missed it, because it's only run against the dev build.

We should consider a couple of things:

1. Is there a way we can prevent bugs (especially those involving styles) from happening in the bundle, but not in the dev build?
2. Should we consider running tests against the bundled output, since that's what users will be consuming?

**Comment by siddharthkp** [comment]
I don't think it's an issue of dev build vs prod build.

We can see this bug in dev versions of manage and docs as well now.

**Comment by landitus** [comment]
Closing it as we are not providing a bundle anymore.
