### ISSUE TITLE
Guiding principles of cosmos components to help make decisions

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#65]
It's useful to keep all guiding principles in one place, these influence the smaller decisions we make 😄 

The aim of cosmos is to _help_ designers and developers deliver work faster and better.

&nbsp;

- _Common language for all teams._

	Code (components, tokens, etc.) and design assets (sketch files, icons, etc.) should always have the same naming convention/API and be kept in sync. The documentation is the tool to help bridge the gap between design, engineering and product. 

- _Encourage the best UX/UI practices._

	We should provide guidelines on when to use components and patterns (or not) to ensure consistency throughout our products (and within). 

- _Have meaningful defaults, bake convention in the components._

	Developers should be able to pick a component create the recommended design guideline out of the box. Optimise for ease of implementation. Bonus: Challenge conventions all the time.

- _Provide powerful abstractions while exposing the inner components at the same time._

	It should be easy + fast to build entire pages with cosmos, but at no point should the developer feel limited by the system. If there's a need to go out of the recommended way, they should be able to compose it with the inner/base components.

- _Be open about progress, direction, intentions._

**Comment by landitus** [comment]
I think this should be in the homepage of the docs website

**Comment by nkohari** [comment]
This is now captured in the docs, which is definitely a good spot for it! Any additional updates to it should go there.
