### ISSUE TITLE
Local apps seem to use output of yarn build

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#651]
I was reviewing the new `Checkbox` component, and when running `yarn scripts docs.dev`, it didn't appear in the sidebar of the docs site. After restarting the app a couple of times with no change in behavior, I tried running `yarn build`, after which the `Checkbox` appeared on the sidebar.

Is it possible the local apps are using the production bundle output somehow? It seems like this is similar to the issue we ran into the other day which required removing the `main.js` file from our local copies.

**Comment by siddharthkp** [comment]
Taken care in https://github.com/auth0/cosmos/pull/645

😀
