### ISSUE TITLE
Change the layout of the FormField

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#66]
The current layout of form field breaks when the text label is really long.

![screen shot 2017-12-19 at 11 42 05 am](https://user-images.githubusercontent.com/1863771/34162236-bafdddb2-e4b1-11e7-82b8-e4558374f7db.png)

**Comment by landitus** [comment]
Yes, the last on seems to be right choice. @beneliflo wdyt?

**Comment by siddharthkp** [comment]
Fixed in https://github.com/auth0/cosmos/pull/68
