### ISSUE TITLE
yarn docs.dev does not handle --debug argument

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#662]
I'm experiencing a small issue when trying to debug a component in docs. Based on what we can read on the docs server log, I can use the `--debug` argument to get more info.
```bash
[metadata.dev]  WARN  21 components could use some docs love, run in --debug mode for more info
```
but when I run `yarn scripts docs.dev --debug` I get:
```bash
yarn run v1.5.1
$ nps -s docs.dev --debug
You provided one or more invalid flags: debug Did you forget to put your command in quotes? https://github.com/kentcdodds/nps/blob/v5.9.0/other/ERRORS_AND_WARNINGS.md#invalid-flags
/Users/francocorrea/Code/auth0/cosmos/node_modules/nps/dist/bin-utils/parser.js:112
    throw new Error(`invalid flag(s) passed: ${invalidFlags}`);
    ^

Error: invalid flag(s) passed: debug
    at parse (/Users/francocorrea/Code/auth0/cosmos/node_modules/nps/dist/bin-utils/parser.js:112:11)
    at Object.<anonymous> (/Users/francocorrea/Code/auth0/cosmos/node_modules/nps/dist/bin/nps.js:22:33)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c nps -s docs.dev --debug
Directory: /Users/francocorrea/Code/auth0/cosmos
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/francocorrea/Code/auth0/cosmos/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I guess it is something related to how `nps` handles the argument and passes (or not) to the docs server.

**Comment by siddharthkp** [comment]
Hey!

There are 2 things here:

1. 

> You provided one or more invalid flags: debug Did you forget to put your command in quotes?

`yarn scripts "docs.dev --debug"`

2. That still wouldn't pass the `--debug` to `tooling/metadata` though

Is that something you would like to dig deeper into with nps docs?

**Comment by francocorreasosa** [comment]
It is not actually something I need, but is something that the tool suggests to use:

> [metadata.dev]  WARN  21 components could use some docs love, run in --debug mode for more info

I'd suggest either to make `nps` to pass the argument to `tooling/metadata` or to remove the suggestion message in `docs.dev`.
