### ISSUE TITLE
Add optional close button to Alert component

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#669]
We should add a close button to the `Alert` which would dismiss the alert when clicked:

![](https://user-images.githubusercontent.com/302314/42130414-d17b67d4-7cba-11e8-8d20-e2975f6f002f.png)

This should be optional, and if it isn't present a consuming app can automatically dismiss the alert after a certain time period, etc.

(via @jcenturion)

**Comment by siddharthkp** [comment]
@landitus Should the close button be visible by default (good UX)
