### ISSUE TITLE
Allow link text to be customized in Alert

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#670]
We should add the ability to customize the text used in the link. Right now it is hardcoded to always be "Read more".

The text should be optional and should default to "Read more" if it isn't specified. Maybe the `link` prop accepts either a string (the URL), or an object with a URL and a label?

![](https://user-images.githubusercontent.com/302314/42130422-1b3b1928-7cbb-11e8-8b69-ede4f9c0ea82.png)

(via @jcenturion)

**Comment by siddharthkp** [comment]
Here's what the API should look like:

```jsx
<Alert
	type="warning"
	title="Notice!"
	text="This is an important message!"
	link={{ label: 'Read more here', url: 'https://auth0.com' }}
/>
```

**Comment by landitus** [comment]
I think we need to rephrase this issue to allow total freedom to use text, links and formatting with bold and code inside the alert. This one also falls into the category of needing freeform text as the content will vary a lot. Similiar situation with the Form Field helper text, the Empty state and the Page header text.

We can follow up on this as a the free form text strategy for components before changing the alert as a  standalone.

**Comment by landitus** [comment]
This is already solved! You can add text with formatting and links in the alerts
