### ISSUE TITLE
Add validation and informative errors for enum props

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#671]
Several components accept enum values for props, and then use them as keys into dictionaries. While we are validating prop types using `PropTypes.oneOf()`, this just results in a warning that might be easily missed. The subsequent error that gets logged is cryptic, and doesn't immediately make it apparent that the user's invalid input is the cause.

For example, if you pass an empty string (or any other invalid value) to the `type` prop of Alert, it results in the error:

```
Cannot read property 'background' of undefined
```

(See it in action: https://codesandbox.io/s/7j5zq5yx4q)

We should come up with a way to do runtime validation of enum props and ensure that they are valid before we use them. If they aren't valid, we should throw a more informational error so the user knows that it's their input that's the problem. Maybe we can do this using a HOC? We should be able to get to the `PropTypes` of the component.

Regardless of the approach, we should apply it to a single component, review it to make sure everyone is on board, and then apply it to the rest of the components that use enums. We may want to add additional validation at some point, but this will be a good start.

(via @jcenturion)

**Comment by siddharthkp** [comment]
How do you feel about providing `DebugWrapper` that you can wrap the entire app with.

It has a `componentDidCatch` which returns a custom Error dialog which returns a more useful error. 

In production environment, it returns `React.Fragment` to be transparent.

**Comment by nkohari** [comment]
I like that idea. It'd definitely be nice to automatically skip the runtime checking code in production, if possible.

**Comment by siddharthkp** [comment]
Turns out `componendDidCatch` does not catch `prop-type` warnings because they are not `thrown` out loud.

https://github.com/auth0/cosmos/pull/689 changes that when you use our engine and adds a nice error overlay.

We can replicate that behaviour without the engine, the result might not be as good. Is it something to go after?
