### ISSUE TITLE
Button: Loading spinner should change color (invert?) based on type of button

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#675]
For some types of `Buttons` -- for example `destructive` -- the spinner displayed during the `loading` state isn't very visible:

![](https://user-images.githubusercontent.com/302314/42138734-8a749448-7d58-11e8-8cd5-6a98e8d614be.png)

We should make the spinner more visible in these cases.

**Comment by landitus** [comment]
To solve this one, we can conditionally use the inverted version of the [Spinner](https://auth0-cosmos.now.sh/docs/#/component/spinner) on the `destructive` and `cta` appearances of the Button
