### ISSUE TITLE
Props table in docs shouldn't show children as a prop

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#676]
Right now, we aren't handling the `children` prop that well in docs. For example, in `Heading`:

![screen shot 2018-07-09 at 11 43 56 am](https://user-images.githubusercontent.com/1576/42461030-883a68f4-836d-11e8-8561-f20a409918db.png)

This same behavior is shown in `ButtonGroup`. This is a little confusing, and makes it so the code generated in the playground is incorrect if it's copied and pasted.

Does it make sense to assign `children` a prop type other than `Node` anyway?

(via @jcenturion)

**Comment by siddharthkp** [comment]
On second thoughts, we should not remove `children` from the table.

It's pretty useful in components that accept other components: https://auth0-cosmos.now.sh/docs/#/component/breadcrumb

Instead we should try to make it more useful: 


```js
  children: PropTypes.instanceOf(Breadcrumb.Link)
```

should be represented as 

```
children: React node of type Breadcrumb.Link
```
