### ISSUE TITLE
Spinner: Support different sizes and colors

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#679]
We should support different sizes and colors for the spinner.

(via @jcenturion)

@landitus Can you add a mockup to this issue?

**Comment by landitus** [comment]
**Mockup:**
<img width="744" alt="screen shot 2018-08-16 at 16 14 43" src="https://user-images.githubusercontent.com/239215/44229804-9222dc00-a16f-11e8-9cf8-1a4eb71ab46d.png">

**Sketch file:** 
https://www.dropbox.com/s/enlo8hp1iree33s/Spinner.sketch?dl=0

The `default` size is the larger one, the small one is size `small`

**Comment by landitus** [comment]
Closing as this is all supported.
