### ISSUE TITLE
Support forms inside of dialogs

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#682]
Right now it isn't possible to create a `Dialog` with a `Form` inside it. This is a pretty important use case, so we should fix this problem soon. 😄 

The trouble is that `Dialog` has its own footer and buttons which aren't the same as the `Form` buttons. We want to support the use case of a `Dialog` that *doesn't* have a form embedded in it -- for example, we'll want OK/Cancel and Yes/No/Cancel dialogs at a minimum.

Worst case, we could introduce a new `FormDialog`, but there might be a better way to handle this problem.

**Comment by landitus** [comment]
This was addressed in https://github.com/auth0/cosmos/pull/986
