### ISSUE TITLE
Button has a bug when setting the URL prop

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#692]
The Button has an undesired visual change when the URL prop is set. Check the demo:

![kapture 2018-07-16 at 11 26 59](https://user-images.githubusercontent.com/239215/42764216-73131d9e-88eb-11e8-8cc3-3332be80f43a.gif)

**Comment by siddharthkp** [comment]
Fixed in https://github.com/auth0/cosmos/pull/728
