### ISSUE TITLE
Create Dropdown component

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#702]
We need to create a `Dropdown` component, representing a drop-down menu of items. These items might be links to other URLs, or they might be freeform and just have `onClick` callbacks. We also need to support a separator element.

An example API (feel free to adjust this as needed):

```jsx
<Dropdown>
  <Dropdown.Option icon="..." link="/some/other/url">Option 1</Dropdown.Option>
  <Dropdown.Option icon="..." onClick={...}>Option 2</Dropdown.Option>
  <Dropdown.Separator />
  <Dropdown.Option icon="..." onClick={...}>Option 3</Dropdown.Option>
</Dropdown>
```

* [x] Add example image (@landitus)

**Comment by landitus** [comment]
### Proposed Name
Dropdown Menu

### Design 
The design can be seen here: https://www.dropbox.com/s/jbduxd74497rafr/DropdownNavigation.sketch?dl=0

<img width="809" alt="screen shot 2018-07-23 at 11 46 01" src="https://user-images.githubusercontent.com/239215/43089429-f40866fe-8e7a-11e8-97da-4f281b2e9d41.png">

### Examples: 
For examples of usage (not design), we can cover the [...] 3 dots example inside a Table (check @jcenturion test). This will probably be the most common usage.

<img width="890" alt="screen shot 2018-07-23 at 13 31 13" src="https://user-images.githubusercontent.com/239215/43090229-325e3670-8e7d-11e8-9dd7-760340e95b27.png">

**Other usage examples**
<img width="582" alt="screen shot 2018-07-23 at 13 36 37" src="https://user-images.githubusercontent.com/239215/43090542-0e1d45a2-8e7e-11e8-9543-1a51f0fd5314.png">
<img width="222" alt="screen shot 2018-07-23 at 13 37 06" src="https://user-images.githubusercontent.com/239215/43090546-1128444a-8e7e-11e8-84b3-ee3c387387bf.png">
<img width="837" alt="screen shot 2018-07-23 at 13 37 26" src="https://user-images.githubusercontent.com/239215/43090547-1320bc82-8e7e-11e8-9382-4c90cda6e008.png">

The user dropdown is a way more advanced component, but has the same usage.
<img width="279" alt="screen shot 2018-07-23 at 13 38 28" src="https://user-images.githubusercontent.com/239215/43090612-4324d1d4-8e7e-11e8-9fe2-028dff3e8fcb.png">


### References
Here's an interesting take on similar components:
- https://ant.design/components/dropdown/#
- https://polaris.shopify.com/components/overlays/popover#navigation

### Questions:
- How the dropdown relates to the button? A lot of examples are a combination of the button and the dropdown.
