### ISSUE TITLE
Add a size prop to TextInput which can support normal or small

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#707]
This is primarily needed in the `PaginationToolbar`. We need to support a smaller version of `TextInput`.

* [x] Add mockup image (@landitus)

**Comment by nkohari** [comment]
@landitus Can you give me a mockup of what this should look like? I can tackle it today.

**Comment by landitus** [comment]
<img width="652" alt="screen shot 2018-07-27 at 12 12 59" src="https://user-images.githubusercontent.com/239215/43329370-8a4da138-9196-11e8-933b-eea965a17e43.png">

The size of the input that we need is called `compressed`. It matches the height of the compressed  buttons and will be used in the pagination toolbar.

As additional tasks, we can:
- Update the overview page here:

<img width="919" alt="screen shot 2018-07-27 at 12 16 13" src="https://user-images.githubusercontent.com/239215/43329491-e2f09872-9196-11e8-879a-407a4de3b399.png">

- Add to storybook a test with the input and buttons sizes side by side (like the screenshot) to check they always match
