### ISSUE TITLE
Fix issues with global styles and resets in styleguide/css apps

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#732]
We have noticed style overrides when using Cosmos in an application that currently has resets, the Styleguide and local globals styles  that affect globally buttons and inputs. 

We have talked about many strategies for the long term, but we want a hot and simple solution to apply now :) The first step is to test a solution in a branch in the product before merging and releasing a fix.

**Comment by landitus** [comment]
The problem we noticed comes from differences in the line-height between Styleguide and Cosmos. This disparity can only grow, so it makes sense to explore how to introduce changes. So far, we have done some **in-product testing** with @cristiandouce and the **wrapper approach** seems to work: styles from the app remain untouched and Cosmos components get shielded and appear with the proper `line-height`.

### Test
1. Cosmos resets are disabled in the application.
2. A wrapper component with these are the exact CSS rules.

```
const CosmosResetWrapper = styled.div `
  /* Cosmos resets */
  * {
    box-sizing: border-box;
  }

  strong, em {
    font-weight: ${fonts.weight.bold};
  }

  body, input, textarea, button, select {
    font-family: ${fonts.family.text};
    font-weight: ${fonts.weight.normal};
    font-size: 14px;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  /* Cosmos globals */
  [class^="sc-"] {
    line-height: ${misc.lineHeight};
  } 
`

const BackwardsCompatibilityStyles = styled(CosmosResetWrapper)`
  /* should we need to override stuff */
`

/* Usage 
<BackwardsCompatibilityStyles>
  ... <Pages>
</BackwardsCompatibilityStyles>
*/

```

 Let's try them in-product from an up-to-date branch before merging in.

### Test case
Any form with labels on the left.

<img width="597" alt="screen shot 2018-08-08 at 11 59 58" src="https://user-images.githubusercontent.com/239215/43845531-98ef5a36-9b02-11e8-85e1-ad926e0c041d.png">

**Comment by siddharthkp** [comment]
Tacked in https://github.com/auth0/cosmos/pull/776
