### ISSUE TITLE
Add example to docs of using PaginationToolbar to page results in ResourceList and Table

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#734]
Eventually, we want to directly support embedding the toolbar in the `ResourceList` and `Table`, but in the meantime users can use the two components individually.

We should add an example to the documentation for both `ResourceList` and `Table` to demonstrate how to go about this. The example component should render the list/table component and the pagination component, and manage the state/event handlers to page the data in the list/table.

**Comment by francocorreasosa** [comment]
Done!

**Comment by francocorreasosa** [comment]
Resource List: https://auth0-cosmos-master.now.sh/docs/#/component/pagination-toolbar#usage-with-resource-lists
Table: https://auth0-cosmos-master.now.sh/docs/#/component/pagination-toolbar#usage-with-table
