### ISSUE TITLE
Button text wraps to another line if compressed

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#740]
As discovered in #739 after making tweaks to the `Stack` used in tests.

**Comment by siddharthkp** [comment]
[Playground example](https://auth0-cosmos-docs-playground.now.sh/docs/#/playground?code=%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Container%20=%20styled.div%60%250A%20%20background:%20pink;%250A%20%20padding:%2010px;%250A%60%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20(%250A%20%20%20%20%3Cdiv%3E%250A%250A%20%20%20%20%20%20Take%20all%20the%20width%20you%20need%250A%20%20%20%20%20%20%3CContainer%3E%250A%20%20%20%20%20%20%20%20%3CButtonGroup%3E%250A%20%20%20%20%20%20%20%20%20%20%3CButton%20appearance=%22primary%22%20icon=%22copy%22%3ESave%20changes%3C/Button%3E%250A%20%20%20%20%20%20%20%20%20%20%3CButton%20appearance=%22destructive%22%20icon=%22delete%22%3EDelete%20button%3C/Button%3E%250A%20%20%20%20%20%20%20%20%3C/ButtonGroup%3E%250A%20%20%20%20%20%20%3C/Container%3E%250A%250A%20%20%20%20%20%20%3Cbr/%3E%250A%20%20%20%20%20%20Confined%20spaces%20make%20the%20buttons%20wrap%250A%20%20%20%20%20%20%3CContainer%20style=%7B%7B%20width:%20'200px'%20%7D%7D%3E%250A%20%20%20%20%20%20%20%20%3CButton%20appearance=%22primary%22%20icon=%22copy%22%3ESave%20changes%3C/Button%3E%250A%20%20%20%20%20%20%20%20%3CButton%20appearance=%22destructive%22%20icon=%22delete%22%3EDelete%20button%3C/Button%3E%250A%20%20%20%20%20%20%3C/Container%3E%250A%20%20%20%20%20%20%250A%20%20%20%20%20%20%3Cbr/%3E%250A%20%20%20%20%20%20Using%20a%20button%20group%20makes%20buttons%20wrap%20inside%20themselves!%250A%20%20%20%20%20%20%3CContainer%20style=%7B%7B%20width:%20'200px'%20%7D%7D%3E%250A%20%20%20%20%20%20%20%20%3CButtonGroup%3E%250A%20%20%20%20%20%20%20%20%20%20%3CButton%20appearance=%22primary%22%20icon=%22copy%22%3ESave%20changes%3C/Button%3E%250A%20%20%20%20%20%20%20%20%20%20%3CButton%20appearance=%22destructive%22%20icon=%22delete%22%3EDelete%20button%3C/Button%3E%250A%20%20%20%20%20%20%20%20%3C/ButtonGroup%3E%250A%20%20%20%20%20%20%3C/Container%3E%250A%20%20%20%20%20%20%250A%20%20%20%20%3C/div%3E%250A%20%20)%250A%7D%250A%250Arender(Example)%250A) to help narrow this down

Should buttons have `min-width` or should they adapt to their parent? 
@landitus 👋

**Comment by landitus** [comment]
Wow, love the playground example!! 

I believe it will have to adapt to the parent. Example 1 and 2 are accepted, as the user has to give them enough space to flow. Example 3 looks weird, and should look like number 2.

**Comment by nkohari** [comment]
It seems like the rule should just be: content within the button shouldn't wrap, but the buttons themselves can wrap. (That is, a button is an atomic unit from a whitespace standpoint.)

**Comment by landitus** [comment]
agree, well put!
