### ISSUE TITLE
Provide a way to add text with formatting in Empty State, Page Header, Alert. 

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#753]
Empty State, Page Header, Alert have a way to add text but no formatting is allowed. These components will need to allow text with either **bold**, [link](url) or sometimes `code`. Note that [Form field helper text](https://auth0-cosmos.now.sh/docs/#/component/form-field#help-text) has a way, but it's wonky. Maybe it can be reviewed as well.

<img width="834" alt="screen shot 2018-08-02 at 16 45 49" src="https://user-images.githubusercontent.com/239215/43607065-8da7acde-9673-11e8-82e7-ef3ebb6746f5.png">

Either way, it's interesting to check if some API decisions are shared or not.

**Comment by nkohari** [comment]
We discussed allowing users to pass in children to these components, so the content can be open-ended:

```jsx
<EmptyState ...props... >
  Whatever <strong>content</strong> they want to display goes here
</EmptyState>
```

This means we'll lose a little control over the design decisions, but it'll be capable of supporting whatever users want to throw at it.
