### ISSUE TITLE
State not being updated inside Tabs

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#754]
Reported by @nicogarcia. 

State is not being updated inside Tabs. Check the [Playground example](https://auth0-cosmos-master.now.sh/docs/#/playground?code=%0A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%0A%0A%0Aclass%20Example%20extends%20React.Component%20{%0A%20%20constructor()%20{%0A%20%20%20%20this.state%20=%20{%20greeting:%20'Hello'%20}%0A%20%20}%0A%0A%20%20render()%20{%0A%20%20%20%20return%20(%0A%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%3CHeading%20size={2}%3EState%20not%20being%20updated%20inside%20cosmos%20tabs%3C/Heading%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20Greeting%20outside%20tab:%20{this.state.greeting}%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%3CTabs%3E%0A%20%20%20%20%20%20%20%20%3CTabs.Tab%20label=%22Profile%22%3EGreeting%20inside%20tab:%20{this.state.greeting}%3C/Tabs.Tab%3E%0A%20%20%20%20%20%20%3C/Tabs%3E%20%20%0A%20%20%0A%20%20%20%20%20%20%3CButton%20onClick={()%20=%3E%20this.setState({%20greeting:%20%22Bye%22})}%3EUpdate%20greeting%3C/Button%3E%0A%20%20%20%20%3C/div%3E)%0A%20%20}%0A}%0A%0Arender(Example)%0A)

**Comment by francocorreasosa** [comment]
Related to #585
