### ISSUE TITLE
Unit tests for tooltip

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#764]
Testing tooltips is tricky

Because it's only visible in hover, our visual tests don't catch it!

**Comment by landitus** [comment]
This could include tests for **Table** and **Tabs** as they seem to be more adopted.

**Comment by siddharthkp** [comment]
> This could include tests for Table and Tabs as they seem to be more adopted.

Different component, different issues:

https://github.com/auth0/cosmos/issues/861
https://github.com/auth0/cosmos/issues/860
