### ISSUE TITLE
Documentation search is broken

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#775]

**Comment by francocorreasosa** [comment]
Related to #592. This was already fixed and then broke again.

**Comment by siddharthkp** [comment]
@francocorreasosa was this a bad merge?

That one line seems to be there" https://github.com/auth0/cosmos/blob/master/internal/docs/sidebar/children.js#L27

**Comment by francocorreasosa** [comment]
Maybe yes, I can take a look at this again this week.
