### ISSUE TITLE
[Chromatic] Tokens change, color change tests not running properly

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#787]
Was doing a single color change that should trigger a bunch of changes (inputs, selects, etc) but the chromatic shows a weird change in Breadcrumb. 

- https://github.com/auth0/cosmos/pull/786
- https://www.chromaticqa.com/build?appId=5aba7f6a07f95800202658ff&number=660

I'm holding off the color change till we get the tests right, so I marked the PR as `don't merge`

**Comment by siddharthkp** [comment]
Breadcrumbs is showing up because it wasn't approved before merging https://github.com/auth0/cosmos/pull/767

(unapproved master stories leak out to future PRs)

**Comment by landitus** [comment]
Cool, and what about the actual test that should give out many changes to approve?

**Comment by siddharthkp** [comment]
Got a reply. Yep it's a little too tiny for the diffing to catch

> Hey Sid, I took a closer look at this and it seems like a false negative due to the anti-aliasing detection in our diff algorithm.
I am going to be reworking this anyway in the next few weeks and I'll aim to solve this as part of that.
Cheers,
Tom

There's not much for us to do here other than wait
