### ISSUE TITLE
Load missing fonts in DISABLE_COSMOS_GLOBALS mode

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#792]
In `DISABLE_COSMOS_GLOBALS` mode,

The styleguide load Fakt-Normal and Fakt-Bold, but not Fakt-Medium and Roboto Mono (these was introduced in cosmos)

This makes buttons and inputs (and a few other components) look weird

We should load them even in `DISABLE_COSMOS_GLOBALS` mode

**Comment by siddharthkp** [comment]
Fixed in https://github.com/auth0/cosmos/pull/814 🎉

**Comment by landitus** [comment]
Is there something to be done here? This card got lost in the 0.5 under "Needs review" :)

**Comment by siddharthkp** [comment]
Nope, I closed it because it was Fixed in #814 🎉

**Comment by landitus** [comment]
Super, removing it from the project then!
