### ISSUE TITLE
Usability testing: Table

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#800]
You can drop your feedback in this issue as comments and close it when you're done!

We'll create new issues for changes to be done.

Things to remember: How to pass data, column width + alignment, sorting, dynamic data/pagination

What makes a component _good_ for usage? See https://github.com/auth0/cosmos/issues/794

**Comment by landitus** [comment]
I did a first pass at the table. I can flesh it out with examples or images.

- Bug: How do I set the initial sorted by column. I don’t know how to do it know. Document that example.
- Add support to easily set the alignment of each column's content (align: left, center, right)
- Add support for a loading state (with spinner). Check manage today for the example.
- Add support for an empty state (no data/items displayed)
- Each row has a pointer cursor, but it shouldn't.
- Let’s highlight each row on hover, but leave the cursor in default.
- Question: why can’t I add an element directly into the row (as a children)?
- Docs: Add example for table without any sorting
- Tests: Add test for table without any sorting

**Comment by nkohari** [comment]
Converting these to issues. Some feedback:

1. From a UX standpoint, does it make sense to highlight a table row if clicking it doesn't do anything? Maybe we actually want to highlight the row if it has an `onClick`, or add a prop like `highlightOnHover`?
2. You can't (currently) add rows to `Table` as `children` because it's a fully-data-driven component. Letting users add rows manually would interfere with our ability to sort and page the table. We'd also have to re-do the API, because the children of `Table` are `Table.Columns`, rather than `Table.Rows` (and `Table.Cells`).

**Comment by nkohari** [comment]
After looking back at the code, it looks like it was intended for the `cursor: pointer` style to be applied only if `onRowClick` was set, but there's currently a bug that's causing it to be set all the time. I'll fix the bug for now, but if we want to change how it works that's fine too.

**Comment by nkohari** [comment]
I know that the original request was for table column alignment not to affect headers, but I think we may want to consider it. For example, the last two columns of this table are right-aligned:

![screen shot 2018-08-20 at 9 05 50 am](https://user-images.githubusercontent.com/1576/44342230-554d3280-a458-11e8-863a-3d0d66d9aea9.png)

**Comment by landitus** [comment]
Thanks! Two things:
- Can we change and make the row highlight on hover, even if there is no onClick? This is the behaviour working today. I believe its a feature to make the row easy to read as you hover on it. The cursor would remain the default, as this PR makes sure.
- The hover row color should be #FAFAFA. We can check in the tokens or add it to the Table with a comment to later tokenize it.

**Comment by landitus** [comment]
Found another one:
- When the column is sortable but not active, when you hover on the column header, the sort arrow should appear to denote that the column is sortable.

<img width="471" alt="screen shot 2018-08-23 at 12 25 18" src="https://user-images.githubusercontent.com/239215/44535229-ea0d9580-a6cf-11e8-90d9-7addf4bd0532.png">

**Comment by landitus** [comment]
> From a UX standpoint, does it make sense to highlight a table row if clicking it doesn't do anything? Maybe we actually want to highlight the row if it has an onClick, or add a prop like highlightOnHover?

I did think the same at first. But the actual behaviour of highlighting the row on hover (even if the row it's not clickable) seems to help read the row data more clearly. I think we could add it for consistency sake and I'll be sure to document this with Design.

**Comment by landitus** [comment]
- Add support to truncate long text (if desired) and avoid having two lines. We could think if this is via a helper component or a prop to the column.
- Let's stress test cell content with and without truncation to check how the table behaves with long content

**Comment by nkohari** [comment]
I checked off the items on the original checklist that have been either implemented in a PR, or are tracked in other issues.
