### ISSUE TITLE
Add loading indicator to Table

### ISSUE THREAD

**Issue by nkohari** [auth0/cosmos#827]
We should add a `loading` prop to `Table` which, if `true`, displays a loading indicator.

**Comment by francocorreasosa** [comment]
How would the loading indicator look like? Do we have a mockup or similar for this? cc @landitus

**Comment by francocorreasosa** [comment]
Will use examples from current Dashboard.

**Comment by landitus** [comment]
<img width="908" alt="screen shot 2018-08-23 at 11 47 06" src="https://user-images.githubusercontent.com/239215/44532766-4e2d5b00-a6ca-11e8-8459-a459593dfe3f.png">

Awesome. As you can see, we don't have that spinner yet, but the current one will do for now. We have a task to add the larger one, so we can later replace it. the spacing from the top and the spinner is 32px (spacing-4 I believe)

**Comment by francocorreasosa** [comment]
Looks like this while we don't have the big spinner:
![image](https://user-images.githubusercontent.com/4152942/44601596-590fea80-a7b3-11e8-8fe4-c28e37c43a95.png)

**Comment by siddharthkp** [comment]
This was implemented ✨ 

https://auth0-cosmos.now.sh/docs/#/component/table
