### ISSUE TITLE
Component versioning for sketch libraries

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#83]
It's easy to version and publish individual components in code. How does that play with our sketch library is something we'll have to figure out 🤔 

Potential solution: create a new symbol for archiving components while pointing default to the latest version

```
button@2.1
button@2.0
button@1.5

button --> latest --> button@2.1
```

**Comment by landitus** [comment]
Actually with Sketch Libraries we should be covered, not by versioning, but from having pulled (or not) the latest library version available. You either choose to stay up to date to the system or you keep the version you where working on 💅

**Comment by landitus** [comment]
Yesterday we did a basic Sketch Libraries test and it's really cool 😉 https://www.sketchapp.com/docs/libraries/

**Comment by nkohari** [comment]
@siddharthkp Do we still want this issue open?

**Comment by siddharthkp** [comment]
Err, kind of. But not really
