### ISSUE TITLE
Hide buttons from Pagination Toolbar

### ISSUE THREAD

**Issue by claudiahdz** [auth0/cosmos#833]
It would be nice to hide the buttons of the pagination toolbar when you're on the first or last page. Keeping them both visible is misleading because it makes the user believe there are still more pages to go. If you're in the first page, the left button should be hidden and if you're in the last... the right button.

<img width="845" alt="screen shot 2018-08-20 at 21 43 09" src="https://user-images.githubusercontent.com/1660769/44359970-0c31c880-a4c2-11e8-8d1e-2e1dce3ce51a.png">

**Comment by francocorreasosa** [comment]
@landitus What do you think?

**Comment by francocorreasosa** [comment]
Hey @claudiahdz! Thank you for the suggestion! @landitus what do you think?

**Comment by siddharthkp** [comment]
Makes sense!

Here's my UX take:

1. If there is only one page, hide entire pager: The user doesn't have to see it at all.

2. If there are multiple pages, disable (don't hide) the unnecessary button

	When actions shift positions, it creates a jarring experience for the user. 
	
![image](https://user-images.githubusercontent.com/1863771/44387130-493d9f80-a542-11e8-8d79-eda66b2aff7f.png)

**Comment by landitus** [comment]
I agree! Example with the **disabled** button looks way better than the first one. This something we can bake in Pagination Toolbar.

**Comment by francocorreasosa** [comment]
Awesome! Let's do it :)
