### ISSUE TITLE
Button with icon only: Icon will be blue, not button's text color

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#841]
The button component forces a special size and color when the content is an icon:

/core/components/atoms/button/button.js@master#L158-L163

In cases like the close btn on a dialog and others, this is not desired. I suggest removing this declaration, and add a new appearance for "action" btns that looks like regular text.

Therefore we can create things like kebab menus or close btns.

Before resolving this issue please make sure the overwrite on the dialog component for the close btn is removed.

**Comment by jvelezpo** [comment]
Hello @francocorreasosa, 
Can you give me more detail here please, i see that when there is no text the icon goes blue, is that what it needed to be prevented?

![image](https://user-images.githubusercontent.com/1050904/46376877-c8071b80-c65c-11e8-8d44-1d0d1de5e383.png)


![image](https://user-images.githubusercontent.com/1050904/46376883-cb9aa280-c65c-11e8-98de-22519db0e951.png)
