### ISSUE TITLE
Avatar can't be centered horizontally

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#843]
Had some issues with alignment: I was trying to align it in the center of the div, doesn't seem to work. [playground link](https://auth0-cosmos.now.sh/docs/#/playground?code=//%20this%20should%20shift%20the%20content%20of%20the%20children%20%F0%9F%A4%94%250Aconst%20Container%20=%20styled.div%60%250A%20%20text-align:%20center;%250A%60%250A%250Aclass%20App%20extends%20React.Component%20%7B%250A%20%20constructor()%20%7B%250A%20%20%20%20super()%250A%20%20%20%20this.state%20=%20%7B%20members:%20%5B%5D%20%7D%250A%20%20%7D%250A%20%20componentDidMount()%20%7B%250A%20%20%20%20fetch('https://api.github.com/orgs/auth0/members?per_page=5').then(response%20=%3E%20%7B%250A%20%20%20%20%20%20response.json().then(members%20=%3E%20this.setState(%7B%20members%20%7D))%250A%20%20%20%20%7D)%250A%20%20%7D%250A%20%20render()%20%7B%250A%20%20%20%20return%20(%250A%20%20%20%20%20%20%3CContainer%3E%250A%20%20%20%20%20%20%20%20%3CAvatar%250A%20%20%20%20%20%20%20%20%20%20type=%22resource%22%250A%20%20%20%20%20%20%20%20%20%20size=%22xxlarge%22%250A%20%20%20%20%20%20%20%20%20%20image=%22https://cdn.auth0.com/website/assets/pages/press/img/resources/auth0-glyph-109d4c73c4.svg%22%250A%20%20%20%20%20%20%20%20/%3E%250A%20%20%20%20%20%20%20%20%3CTable%20items=%7Bthis.state.members%7D%3E%250A%20%20%20%20%20%20%20%20%20%20%3CTable.Column%20field=%22avatar_url%22%20width=%2230px%22%3E%250A%20%20%20%20%20%20%20%20%20%20%20%20%7Bmember%20=%3E%20%3CAvatar%20type=%22user%22%20image=%7Bmember.avatar_url%7D%20/%3E%7D%250A%20%20%20%20%20%20%20%20%20%20%3C/Table.Column%3E%250A%20%20%20%20%20%20%20%20%20%20%3CTable.Column%20field=%22login%22%20title=%22Name%22%20/%3E%250A%20%20%20%20%20%20%20%20%20%20%3CTable.Column%20field=%22role%22%20title=%22Role%22%20%3E%250A%20%20%20%20%20%20%20%20%20%20%20%20%7Bmember%20=%3E%20(member.site_admin%20?%20'Admin'%20:%20'Member')%7D%250A%20%20%20%20%20%20%20%20%20%20%3C/Table.Column%3E%250A%20%20%20%20%20%20%20%20%3C/Table%3E%250A%20%20%20%20%20%20%3C/Container%3E%250A%20%20%20%20)%250A%20%20%7D%250A%7D%250A%250Arender(App))

**Comment by landitus** [comment]
Mmm, interesting. Are you aiming to center the Avatar on that page or the Avatar block on the cell? or both? The first one it's something we should support. The second, the example is not something we should encourage, as the block is definitely an aligned to the right composition. Still it's interesting if we could be able to support it.

**Comment by siddharthkp** [comment]
I was trying to only center the big avatar horizontally

haven't added avatar block yet

**Comment by landitus** [comment]
Good!

**Comment by siddharthkp** [comment]
This should be tackled in Layouts https://github.com/auth0/cosmos/issues/1108
