### ISSUE TITLE
Heading size prop is not consistent across docs and TS spec

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#858]
_(via @cristiandouce)_

Using `<Header size={3} />` will throw this warning:
![image](https://user-images.githubusercontent.com/4152942/44551178-b9902080-a6fc-11e8-8daf-893c8e948a79.png)

and using `<Header size="3" />`  will throw the following runtime error:
<img width="380px" src="https://user-images.githubusercontent.com/4152942/44551200-cf054a80-a6fc-11e8-8f0e-e20a61e28d0b.png" />

Although, in the docs the example is using a string to represent the size prop and it works just fine:
![image](https://user-images.githubusercontent.com/4152942/44551244-ee03dc80-a6fc-11e8-8236-cb20ecc18bb6.png)

**Comment by siddharthkp** [comment]
Why does `<Header size={3} />` throw a warning? That seems like the right usage


`<Header size="3" />` is wrong and throws a warning in the docs:

```
Failed prop type: Invalid prop `size` of value `1` supplied to `Heading`, expected one of [1,2,3,4].
```

I'll update the docs 😅

**Comment by siddharthkp** [comment]
Keeping this open until we fix Part 1 of the problem

Moving this to `Project: Backlog`
