### ISSUE TITLE
Need a version switcher to the docs

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#863]
_We knew we'll have to add this one day. Well, here's the day_

Reported by @claudiahdz 

She copied code from the docs (v0.4.0), but it didn't work because manage uses 0.3.3. Even though the API is backward compatible, it can't support future examples of course

I think this would be a pretty common use case! We wouldn't expect folks to upgrade the same day we release.

Slack conversation: https://auth0.slack.com/archives/GBWHTA692/p1535383306000100

**Comment by francocorreasosa** [comment]
Done
