### ISSUE TITLE
Changing the message of a hidden (dismissed) alert, won't make it visible again.

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#864]
_(vía @mostekcm)_

Dismiss the Alert and then change the message, the Alert won't appear again.

https://auth0-cosmos.now.sh/docs/#/playground?code=%250Aclass%20Example%20extends%20React.Component%20%7B%250A%20%20constructor(props)%20%7B%250A%20%20%20%20super(props);%250A%20%20%20%20this.state%20=%20%7Bmessage:%20%22something%22%7D%250A%20%20%7D%250A%20%20%250A%20%20render()%20%7B%250A%20%20%20%20if%20(!this.state.message)%20return%20null;%250A%20%20%20%20return%20%3C%3E%250A%20%20%20%20%20%20%3Cbutton%20onClick=%7B()%20=%3E%20this.setState(%7Bmessage:%20%22something%20else%22%20%7D)%7D%3Echange%20message%3C/button%3E%250A%20%20%20%20%20%20%250A%20%20%20%20%20%20%3CAlert%20title=%22Success!%22%20type=%22success%22%3E%7Bthis.state.message%7D%3C/Alert%3E%250A%20%20%20%20%3C/%3E%250A%20%20%7D%250A%7D%250A%250Arender(Example)%250A

**Comment by lopno** [comment]
I would like to take a look at this tonight.

**Comment by lopno** [comment]
After looking at the code I couldn't find an elegant solution.
Whether to show the alert is handled by internal state of the Alert component, which I don't think is a very good idea.
Because of this we would have to look at changes in the props and then update the internal state, which could look something like this:
```
  componentDidUpdate(prevProps) {
    if (
      (!this.state.visible &&
        (prevProps.text !== props.text && prevProps.title !== this.props.title)) ||
      JSON.stringify(prevProps.children) !== JSON.stringify(this.props.children) // Ow, my performance
    ) {
      this.setState({
        visible: true
      })
    }
  }
```
The above would work, but would not be very performant.

I think the proper solution would be to handle whether to show the alert in the parent components where it is used, but that would mean that all usages would have to be changed.

Sorry, I would like to have made a nice solution for hacktober. I will take a look at some of the other issues :)

**Comment by siddharthkp** [comment]
Hi @mostekcm 👋 

That's an interesting use case! 

Right now, we don't support bringing back a dismissed Alert. 

Doesn't sound like a thing cosmos should have control over - if the message has changed, it's practically a new Alert.

You can tell React that it should render a new Alert when the message changes - by passing a the key prop `key={this.state.message}` prop. This will work with cosmos as well.

[Here's a demo](https://auth0-cosmos.now.sh/docs/#/playground?code=%250Aclass%20Example%20extends%20React.Component%20%7B%250A%20%20constructor(props)%20%7B%250A%20%20%20%20super(props);%250A%20%20%20%20this.state%20=%20%7Bmessage:%20%22something%22%7D%250A%20%20%7D%250A%20%20%250A%20%20render()%20%7B%250A%20%20%20%20if%20(!this.state.message)%20return%20null;%250A%20%20%20%20return%20%3C%3E%250A%20%20%20%20%20%20%3Cbutton%20onClick=%7B()%20=%3E%20this.setState(%7Bmessage:%20%22something%20else%22%20%7D)%7D%3Echange%20message%3C/button%3E%250A%20%20%20%20%20%20%250A%20%20%20%20%20%20%3CAlert%20key=%7Bthis.state.message%7D%20title=%22Success!%22%20type=%22success%22%3E%7Bthis.state.message%7D%3C/Alert%3E%250A%20%20%20%20%3C/%3E%250A%20%20%7D%250A%7D%250A%250Arender(Example)%250A)
