### ISSUE TITLE
Should button be clickable while it's in loading state?

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#87]
![screen shot 2017-12-22 at 6 10 12 pm](https://user-images.githubusercontent.com/1863771/34312499-62bbaad2-e743-11e7-831b-ec68b621163c.png)

If not, there are 2 ways of doing it:

1. Override `onClick` prop when the `loading` prop is passed
2. You need to pass `loading` and `disabled` both to disable clicks.

**Comment by luisrudge** [comment]
As a future consumer, I expect this to be handled by the lib itself, so passing loading=true would automatically set to disabled (or ignore the onclick)

**Comment by landitus** [comment]
I agree with @luisrudge !

**Comment by nkohari** [comment]
This has been implemented in the current `Button` component.
