### ISSUE TITLE
Docs: Navigation isn't responsive

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#883]
<img width="788" alt="screen shot 2018-09-03 at 8 30 41 pm" src="https://user-images.githubusercontent.com/1863771/44993459-4a49e480-afb8-11e8-8f37-5c98cb56460f.png">

**Comment by adamjang** [comment]
I'll take a look at this.

**Comment by lopno** [comment]
I made a PR to fix this.
I was not sure if @adamjang was still working on it.

**Comment by adamjang** [comment]
I have a solution which uses a hamburger menu similar to the auth0 website, but I won't be able to make the PR until tonight.
