### ISSUE TITLE
Chromatic tests not working

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#890]
Chromatic tests are not working right now.

<img width="731" alt="screen shot 2018-09-03 at 18 21 04" src="https://user-images.githubusercontent.com/239215/45001752-3f865400-afa6-11e8-88ac-dacdecf7ba3b.png">

**Comment by siddharthkp** [comment]
Fixed in https://github.com/auth0/cosmos/pull/851/commits/fb82e453bbce8dc8904b75ed3b47bd640820bef3
