### ISSUE TITLE
Table columns cannot be passed as external children

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#893]
You cannot store columns in a variable and pass that variable as children of the table.

```js
const defaultItems = [
  {
    name: 'Harry Kane',
    goals: 6,
    assists: 0,
    country: '🇬🇧',
    image: 'https://twitter-avatar.now.sh/HKane'
  },
  {
    name: 'Romelu Lukaku',
    goals: 4,
    assists: 1,
    country: '🇧🇪',
    image: 'https://twitter-avatar.now.sh/Romelu_lukaku9'
  },
  {
    name: 'Antoine Griezmann',
    goals: 4,
    assists: 2,
    country: '🇫🇷',
    image: 'https://twitter-avatar.now.sh/AntoGriezmann'
  },
  {
    name: 'Ivan Perišić',
    goals: 3,
    assists: 1,
    country: '🇭🇷',
    image: 'https://twitter-avatar.now.sh/ivanperisic44'
  }
]

const columns = (<>
      <Table.Column field="image" width="50px">
        {item => <Avatar type="user" image={item.image} />}
      </Table.Column>
      <Table.Column field="name" title="Name" width="30%" />
      <Table.Column field="country" title="Country" />
      <Table.Column field="goals" title="Goals" />
      <Table.Column field="assists" title="Assists" />
</>)


const Example = () => {
  return <Table items={defaultItems}>{columns}</Table>
}

render(Example)

```

https://auth0-cosmos.now.sh/docs/#/playground?code=%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20%250Ahere%20*/%250A%250Aconst%20defaultItems%20=%20%5B%250A%20%20%7B%250A%20%20%20%20name:%20'Harry%20Kane',%250A%20%20%20%20goals:%206,%250A%20%20%20%20assists:%200,%250A%20%20%20%20country:%20'%F0%9F%87%AC%F0%9F%87%A7',%250A%20%20%20%20image:%20'https://twitter-avatar.now.sh/HKane'%250A%20%20%7D,%250A%20%20%7B%250A%20%20%20%20name:%20'Romelu%20Lukaku',%250A%20%20%20%20goals:%204,%250A%20%20%20%20assists:%201,%250A%20%20%20%20country:%20'%F0%9F%87%A7%F0%9F%87%AA',%250A%20%20%20%20image:%20'https://twitter-avatar.now.sh/Romelu_lukaku9'%250A%20%20%7D,%250A%20%20%7B%250A%20%20%20%20name:%20'Antoine%20Griezmann',%250A%20%20%20%20goals:%204,%250A%20%20%20%20assists:%202,%250A%20%20%20%20country:%20'%F0%9F%87%AB%F0%9F%87%B7',%250A%20%20%20%20image:%20'https://twitter-avatar.now.sh/AntoGriezmann'%250A%20%20%7D,%250A%20%20%7B%250A%20%20%20%20name:%20'Ivan%20Peri%C5%A1i%C4%87',%250A%20%20%20%20goals:%203,%250A%20%20%20%20assists:%201,%250A%20%20%20%20country:%20'%F0%9F%87%AD%F0%9F%87%B7',%250A%20%20%20%20image:%20'https://twitter-avatar.now.sh/ivanperisic44'%250A%20%20%7D%250A%5D%250A%250Aconst%20columns%20=%20(%3C%3E%250A%20%20%20%20%20%20%3CTable.Column%20field=%22image%22%20width=%2250px%22%3E%250A%20%20%20%20%20%20%20%20%7Bitem%20=%3E%20%3CAvatar%20type=%22user%22%20image=%7Bitem.image%7D%20/%3E%7D%250A%20%20%20%20%20%20%3C/Table.Column%3E%250A%20%20%20%20%20%20%3CTable.Column%20field=%22name%22%20title=%22Name%22%20width=%2230%25%22%20/%3E%250A%20%20%20%20%20%20%3CTable.Column%20field=%22country%22%20title=%22Country%22%20/%3E%250A%20%20%20%20%20%20%3CTable.Column%20field=%22goals%22%20title=%22Goals%22%20/%3E%250A%20%20%20%20%20%20%3CTable.Column%20field=%22assists%22%20title=%22Assists%22%20/%3E%250A%3C/%3E)%250A%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20%3CTable%20items=%7BdefaultItems%7D%3E%7Bcolumns%7D%3C/Table%3E%250A%7D%250A%250Arender(Example)%250A

**Comment by sanketsingh24** [comment]
I'll do this one
