### ISSUE TITLE
Chevron icons are not centered in the icon bounding box

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#902]
thanks for reporting @jcenturion 

![image](https://user-images.githubusercontent.com/239215/45185528-db130100-b200-11e8-9b05-53cf3a335e84.png)

**Comment by andresgalante** [comment]
Remove this:
https://github.com/auth0/cosmos/blob/master/core/components/atoms/button/button.js#L228-L229

Also I'd wouldn't select the icon within the btn. I'd just make a universal selector that adds a margin to any child diregarding of what it is.

Somthing like:

```css
> * not(:last-child) { 
  /* do the margin dance */
}
```

I'd send a PR but I couldn't run the project. Either I am very limited or the contribution guide needs a bit more explaination. My bet is on me been dumb.

**Comment by andresgalante** [comment]
oh, and you might also consider turn the btn to be a flex container instead of `inline-block`, that way you can align items inside the btn better.

Ok I am off :)

**Comment by francocorreasosa** [comment]
This is tricky to fix because actually the icon is centered. But as the chevron is thinner it feels it is not. Should we do an override fix just for chevrons? (checking for the icon name inside the button)
