### ISSUE TITLE
[API Consistency] Remove inconsistency in API for components with icon

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#922]
**Is your feature request related to a problem? Please describe.**
Sometimes when we have a component that accepts an icon as a prop we ask if I should pass a string with the name or an `Icon` instance.

**Describe the solution you'd like**
I propose to make a helper to support both on every case.

**Describe alternatives you've considered**
We may consider to standardize to one of them in all the components, but at the end of the day the same effect will happen.

**Comment by siddharthkp** [comment]
👋 

Changes this to `RFC / Proposal`, `feature-request` and `user-request` are for things requested by our users/developers.

Can you add how this would ideally look like/

**Comment by siddharthkp** [comment]
Related to https://github.com/auth0/cosmos/pull/1071 and https://github.com/auth0/cosmos/pull/1074
