### ISSUE TITLE
Tokenise line-height and font-size together

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#949]
**Is your feature request related to a problem? Please describe.**
We have only one token for line-height (1.6) and 2 tokens for font-size (14, 13)

When we want a different size, we hard code it in the component. This makes it difficult to keep them consistent.

**Describe the solution you'd like**
We should add line-height relative to font-size

Example:
```js
fontSize: {
  default: 14,
  small: 13,
  heading: 36
},
lineHeight: {
  default: 1.6,
  small: 1.8,
  small_compressed: 1.4,
  heading: 1.1
}
```

**Comment by cangoektas** [comment]
I'll take a look at this 🙂

**Comment by cangoektas** [comment]
@siddharthkp I went through `font-size` and `line-height` declarations and realized half-way through that this is probably not something actionable yet. But I made a list of all hardcoded values which I think could be helpful for you guys:

---

<details>
<summary>font-size and line-height declarations (click to open)</summary>

- `atoms/_styled-input/_styled-input.js`
    - StyledInput
        - `font-size: ${props => (props.code ? '13px' : 'inherit')};`

- `atoms/alert/alert.js`
    - Cross
        - `font-size: 1.5em; /* 21px in Storybook and docs */`
        - `line-height: 1;`

- `atoms/badge/badge.js`
    - StyledBadge
        - `font-size: 13px;`
        - `line-height: 1;`

- `atoms/breadcrumb/breadcrumb.js`
    - Wrapper
        - `font-size: 13px;`

- `atoms/button/button.js`
    - Button.Element
        - `font-size: 13px;`
        - `line-height: ${props => getAttributes(props).lineHeight}; /* buttonHeight - 2px */`

- `atoms/code/code.js`
    - StyledCode
        - `font-size: 90%;`
        - `line-height: 18px;`

- `atoms/heading/heading.js`
    - BaseHeading
        - `line-height: 1.3;`
    - StyledHeading[1]
        - `font-size: 36px;`
    - StyledHeading[2]
        - `font-size: 24px;`
    - StyledHeading[3]
        - `font-size: 18px;`
    - StyledHeading[4]
        - `font-size: 14px;`

- `atoms/icon/icon.js`
    - Icon.Element
        - `line-height: 1;`
    - Image
        - `line-height: 1;`

- `atoms/label/label.js`
    - StyledLabel
        - `font-size: 11px;`

- `atoms/paragraph/paragraph.js`
    - StyledParagraph
        - `font-size: 14px;`

- `atoms/switch/switch.js`
    - Label
        - `font-size: ${fonts.size.small};`
        - `line-height: ${height}; /* component height */`

- `atoms/tag/tag.js`
    - StyledTag
        - `font-size: ${fonts.size.small};`
        - `line-height: 1;`

- `atoms/text/text.js`
    - StyledTextSubdued
        - `font-size: 13px;`
    - StyledTextAllCaps
        - `font-size: 12px;`

- `atoms/textarea/textarea.js`
    - StyledTextArea
        - `font-size: ${props => (props.code ? '13px' : 'inherit')};`

- `atoms/tooltip/tooltip.js`
    - StyledTooltip
        - `font-size: 13px;`
        - `line-height: normal;`

---

- `molecules/danger-zone/danger-zone.js`
    - Title
        - `font-size: 1.0714285714em;`

- `molecules/form/fieldset/divider.js`
    - StyledDivider
        - `font-size: 14px;`

- `molecules/form/error.js`
    - Error
        - `font-size: 13px;`

- `molecules/form/help-text.js`
    - StyledHelpText
        - `font-size: 13px;`
        - `line-height: 1.8;`

- `molecules/sidebar/sidebar-link.js`
    - SidebarLink.Element
        - `font-size: 13px;`
        - `line-height: 1;`
</details>

---

**Values used for `font-size`:**

- 1x `90%`
- 1x `36px`
- 1x `24px`
- 1x `21px` (`1.5em`)
- 1x `18px`
- 3x `14px`
- 10x `13px`
- 1x `12px`
- 1x `11px`
- 1x `1.0714285714em`

**Values used for `line-height`:**

- 5x `1`
- 1x `18px`
- 4x `1.3` (each Heading)
- 1x `1.8`
- 1x `normal`

---

What I could do is create tokens for each of the hardcoded values and update the components in a non-breaking way to use the tokens. But I don't think that's what you had in mind with this ticket, right? 😄

**Comment by siddharthkp** [comment]
Wow, this is really helpful too!

The first step to tokenise is _inventory_, so this is really helpful

Next up would be to reduce inconsistency 😅 and make decisions if something is a global token (cosmos-tokens) or a local token (scoped to file)
