### ISSUE TITLE
Tooltip being cut off the visible range by the parent

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#951]
The tooltip component will be cut if the parent is smaller than the tooltip bounding box.

**Comment by siddharthkp** [comment]
@francocorreasosa Screenshot / playground link please

**Comment by francocorreasosa** [comment]
The case is very specific (only when you use `overflow: hidden` on the parent. So I'm not sure if we should fix it.

https://auth0-cosmos-0-6-0.now.sh/docs/#/playground?code=%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20%3Cdiv%20style=%7B%7Bwidth:50,%20height:%2030,%20paddingTop:%2010,%20border:%20'1px%20solid%20black',overflow:'hidden'%7D%7D%3E%250A%20%20%20%20%3CTooltip%20content=%22here%20is%20some%20text%22%3EPreview%3C/Tooltip%3E%250A%20%20%3C/div%3E%250A%7D%250A%250Arender(Example)%250A

**Comment by siddharthkp** [comment]
[Tiny modification to the example](https://auth0-cosmos.now.sh/docs/#/playground?code=/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%0A%0Aconst%20Example%20=%20()%20=%3E%20{%0A%20%20return%20%3Cdiv%20style={{overflow:'hidden',%20padding:%2020,%20border:%20'1px%20solid%20black'}}%3E%0A%20%20%20%20%3CTooltip%20content=%22here%20is%20some%20text%22%3EHover%20over%20me%3C/Tooltip%3E%0A%20%20%3C/div%3E%0A}%0A%0Arender(Example)%0A%0A)

I guess `overflow: hidden` is a valid style that folks might have but it's an edge case. I guess we can get away by calling this a known bug and fixing it at a later stage (because the solution isn't trivial)

- Do we have a dev reported issue for this already?
- Can the dev fix it themselves without needed cosmos?

**Comment by francocorreasosa** [comment]
This bug was reported by @cristiandouce while he was working on UL if I am right.

**Comment by francocorreasosa** [comment]
As reported, this is still happening when using popper, so I guess we'll need to manually take care of this. cc @siddharthkp

**Comment by astanciu** [comment]
Not sure if this is exactly related, but this is also happening:
![image](https://user-images.githubusercontent.com/1675025/51500307-8af59f00-1d9b-11e9-9cde-22b46e805821.png)

**Comment by cristiandouce** [comment]
![image](https://user-images.githubusercontent.com/367429/52218612-c7d09400-2879-11e9-93de-504595167b94.png)

and here is a playgrond [example](https://auth0-cosmos.now.sh/docs/#/playground?code=%250A/*%20you%20have%20access%20to%20all%20cosmos%20components%20here%20*/%250A%250Aconst%20Example%20=%20()%20=%3E%20%7B%250A%20%20return%20%3C%3E%250A%20%20%20%20%3CTooltip%20content=%22here%20is%20some%20text%22%20position=%22right%22%3E%250A%20%20%20%20%20%20%3CCheckbox%250A%20%20%20%20%20%20%20%20name=%22example%22%250A%20%20%20%20%20%20%20%20onChange=%7Bevt%20=%3E%20this.handleChange(evt)%7D%250A%20%20%20%20%20%20%20%20value=%22one%22%250A%20%20%20%20%20%20%20%20checked=%7Btrue%7D%250A%20%20%20%20%20%20%20%20align=%22vertical%22%250A%20%20%20%20%20%20%3E%250A%20%20%20%20%20%20%20%20You%20can%20check%20and%20uncheck%20me%250A%20%20%20%20%20%20%3C/Checkbox%3E%250A%20%20%20%20%3C/Tooltip%3E%250A%20%20%20%20%3CTooltip%20content=%22here%20is%20some%20text%22%20position=%22left%22%3E%250A%20%20%20%20%20%20%3CCheckbox%250A%20%20%20%20%20%20%20%20name=%22example%22%250A%20%20%20%20%20%20%20%20onChange=%7Bevt%20=%3E%20this.handleChange(evt)%7D%250A%20%20%20%20%20%20%20%20value=%22one%22%250A%20%20%20%20%20%20%20%20checked=%7Btrue%7D%250A%20%20%20%20%20%20%20%20align=%22vertical%22%250A%20%20%20%20%20%20%3E%250A%20%20%20%20%20%20%20%20You%20can%20check%20and%20uncheck%20me%250A%20%20%20%20%20%20%3C/Checkbox%3E%250A%20%20%20%20%3C/Tooltip%3E%250A%20%20%3C/%3E%250A%7D%250A%250Arender(Example)%250A)

**Comment by francocorreasosa** [comment]
Fixed by #1458
