### ISSUE TITLE
[API Consistency] Component-as-props API consistency

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/cosmos#972]
# Goal 
The goal here is to have consistency in the way components are passed as props to other components, also to improve maintainability Cosmos.

For example: 

## Icon
Icon prop in Button:
```js
<Button icon={<Icon name="icon-name" />} ... />
```
Icon prop in Alert:
```js
<Alert icon={<Icon name="icon-name" />} ... />
```
or
```js
<Alert icon appearance="warning" ... />
```
for the alert to infer what icon to use.

## Avatar
We may want to keep this one as-is, since there are no other use cases for tha avatar to be passed in as a prop to another component.
```js
<AvatarBlock avatar={<Avatar image="..." type="..." ... />} ... />
```

## Actions
Empty State Action:
```js
<EmptyState action={<Button ... />} ... />
```

Form Actions:
```js
<FormActions 
  primaryAction={<Button ... />} 
  secondaryAction={<Button ... />}
  destructiveAction={<Button ... />} 
  ... 
/>
```

Page Header:
```js
<PageHeader
  primaryAction={<Button ... />} 
  secondaryAction={<Button ... />} 
  ... 
/>
```
# Checklist

- [ ] Alert (icon) #1071 
- [ ] Button (icon)
- [ ] AvatarBlock (type, image from Avatar)
- [x] Dialog (Buttons)
- [ ] Empty State (action)
- [ ] Form Actions (Buttons)
- [ ] Page Header (actions)
- [ ] Resource List (actions)

⚠️ **Important:** We need **not to break backwards compatibility** with current approaches. Current API should be deprecated until 1.0 instead.

For reference: https://twitter.com/jamiebuilds/status/1047968551758323712

**Comment by sanketsingh24** [comment]
Hey! I would like to work on this issue, but would need some more info. Like,for example, We need to migrate "label"  in "Button" component to props? and so on for other components?

**Comment by francocorreasosa** [comment]
@sanketsingh24 The `label` prop in button refers to the Tooltip that is shown when the button is icon only. In this particular case the `<Tooltip />` component should be used I guess. But this particular use case is not confirmed so don't worry :) Thanks anyway!

**Comment by sanketsingh24** [comment]
Thanks for the help, I will look more into this and submit a PR tomorrow :D

**Comment by siddharthkp** [comment]
Hi! I'm not sure if all components would benefit from this

Button is a great example because we would like to control the position/color/etc based on the `appearance` of the button 

I suggest writing down examples for each component in the list - of how the API would look like before making code changes

**Comment by francocorreasosa** [comment]
Icon prop (wherever it is used):
```js
<Component icon={<Icon name="icon-name" />} ... />
```

Avatar Block and Avatar:
```js
<AvatarBlock avatar={<Avatar image="..." type="..." ... />} ... />
```

Empty State Action:
```js
<EmptyState action={<Button ... />} ... />
```

Form Actions:
```js
<FormActions 
  primaryAction={<Button ... />} 
  secondaryAction={<Button ... />}
  destructiveAction={<Button ... />} 
  ... 
/>
```

Page Header:
```js
<PageHeader primaryAction={<Button ... />} secondaryAction={<Button ... />} ... />
```

**Comment by siddharthkp** [comment]
I don't think the goal should be to move to a _component-instance-as-props API_ all across. 

**That's a goal that starts with a solution in mind, not a problem.**

How I see it, we need to look at use-cases for each type of feature. 

Example: Adding an icon should feel the same for a button and input. Adding an action should feel the same for empty state and page header.

**Comment by francocorreasosa** [comment]
> Example: Adding an icon should feel the same for a button and input. Adding an action should feel the same for empty state and page header.

I think this is the goal actually. My bad for not clarifying it from the start.

**Comment by landitus** [comment]
Should we have a consistent way of doing the api *and* also cases where we close it to only allow a simple name where the design is closed on purspose? 

I think we can benefit from both approaches where it makes sense. The example of the icon an the button fits the closed design choose choice by the system, where the page header having a full button or object may allow for some needed flexibility and composability (like passing a dropdown button in the future)

I can help to pick a design strategy for each if it helps clarify

**Comment by francocorreasosa** [comment]
I like both approaches and would like to keep them both, but that does not help for consistency.

In any case:
```js
<Component icon={<Icon name="something"} ... />
```
is exactly the same as:
```js
<Component icon="something" ... />
```

as `Component` will add the required props to `Icon` to make it look as it should to match `Component`'s styles.

**Comment by siddharthkp** [comment]
Left feedback about this on the other PR 😅

https://github.com/auth0/cosmos/pull/1074#issuecomment-437307460
