### ISSUE TITLE
"yarn i" giving "not found" error

### ISSUE THREAD

**Issue by Axle7XStriker** [auth0/cosmos#976]
**Describe the bug**
When I run the `yarn i` command it runs the `nps-i` command which gives a "not found" error. 

**Expected behavior**
Since I am new to this project I can't tell what exactly should happen but based on instructions given I am assuming it to be related to the listing of dev scripts.

**Cosmos version:**
v0.6.0

**Comment by cangoektas** [comment]
Can confirm. I had the same issue and thought maybe there was something wrong with my setup. 🤔

**Comment by siddharthkp** [comment]
Whoops sounds like a missing dependency: [`nps-i`](https://www.npmjs.com/package/nps-i)

**Comment by Ashiroq** [comment]
This seems like a simple thing to solve. I'm not used to yarn workspaces so, should I just add `nps-i` to root or to some workspace?

**Comment by siddharthkp** [comment]
Yep, `nps-i` should be devDependency for the entire project (root)
