### ISSUE TITLE
When tab lable name is too big , label is not truncated or wrapped. 

### ISSUE THREAD

**Issue by jmahesh123** [auth0/cosmos#987]
**Describe the bug**
We have added large text to the label of tab. The text continues to flow and page gets distorted

**Expected behavior**
Label should be truncated or gets wrapped to next line

**Screenshots**
<img width="1128" alt="tab_label_issue" src="https://user-images.githubusercontent.com/5052103/46915144-b05a5c00-cfa7-11e8-839b-cf1b57f29a51.png">

**Comment by siddharthkp** [comment]
Not sure, if this is a realistic use case. Going to close this issue.

Feel free to re-open if you disagree
